INSERT ALL
INTO author (author_name, author_id) VALUES ('A. Bartlett Giamatti', 1)
INTO author (author_name, author_id) VALUES ('A. Elizabeth Delany', 2)
INTO author (author_name, author_id) VALUES ('A. Merritt', 3)
INTO author (author_name, author_id) VALUES ('A. Roger Merrill', 4)
INTO author (author_name, author_id) VALUES ('A. Walton Litz', 5)
INTO author (author_name, author_id) VALUES ('A.B. Yehoshua', 6)
INTO author (author_name, author_id) VALUES ('A.D.P. Briggs', 7)
INTO author (author_name, author_id) VALUES ('A.E. Cunningham', 8)
INTO author (author_name, author_id) VALUES ('A.E. van Vogt', 9)
INTO author (author_name, author_id) VALUES ('A.G. Pasquella', 10)
INTO author (author_name, author_id) VALUES ('A.H. Armstrong', 11)
INTO author (author_name, author_id) VALUES ('A.J. Arberry', 12)
INTO author (author_name, author_id) VALUES ('A.J. Ayer', 13)
INTO author (author_name, author_id) VALUES ('A.J. Jacobs', 14)
INTO author (author_name, author_id) VALUES ('A.J. McAllister', 15)
INTO author (author_name, author_id) VALUES ('A.M. Dellamonica', 16)
INTO author (author_name, author_id) VALUES ('A.M. Homes', 17)
INTO author (author_name, author_id) VALUES ('A.N. Roquelaure', 18)
INTO author (author_name, author_id) VALUES ('A.N. Wilson', 19)
INTO author (author_name, author_id) VALUES ('A.R. Braunmuller', 20)
INTO author (author_name, author_id) VALUES ('A.R. Taylor', 21)
INTO author (author_name, author_id) VALUES ('A.S. Byatt', 22)
INTO author (author_name, author_id) VALUES ('A.T. Hatto', 23)
INTO author (author_name, author_id) VALUES ('A.V. Miller', 24)
INTO author (author_name, author_id) VALUES ('Aaron Anderson', 25)
INTO author (author_name, author_id) VALUES ('Aaron Asher', 26)
INTO author (author_name, author_id) VALUES ('Aaron Medwin', 27)
INTO author (author_name, author_id) VALUES ('Aaron Rosenberg', 28)
INTO author (author_name, author_id) VALUES ('Aaron Shepard', 29)
INTO author (author_name, author_id) VALUES ('Abbe Wool', 30)
INTO author (author_name, author_id) VALUES ('Abbie Hoffman', 31)
INTO author (author_name, author_id) VALUES ('Abdul Rahman Munif', 32)
INTO author (author_name, author_id) VALUES ('Abdul-Karim Mustapha', 33)
INTO author (author_name, author_id) VALUES ('Abigail Adams', 34)
INTO author (author_name, author_id) VALUES ('Abigail Thomas', 35)
INTO author (author_name, author_id) VALUES ('Abolqasem Ferdowsi', 36)
INTO author (author_name, author_id) VALUES ('Abraham Lincoln', 37)
INTO author (author_name, author_id) VALUES ('Abraham Moore', 38)
INTO author (author_name, author_id) VALUES ('Adam Sexton', 39)
INTO author (author_name, author_id) VALUES ('Adam Drozdek', 40)
INTO author (author_name, author_id) VALUES ('Adam Gauntlett', 41)
INTO author (author_name, author_id) VALUES ('Adam Ginsberg', 42)
INTO author (author_name, author_id) VALUES ('Adam Golaski', 43)
INTO author (author_name, author_id) VALUES ('Adam Gopnik', 44)
INTO author (author_name, author_id) VALUES ('Adam Hargreaves', 45)
INTO author (author_name, author_id) VALUES ('Adam Haslett', 46)
INTO author (author_name, author_id) VALUES ('Adam Hochschild', 47)
INTO author (author_name, author_id) VALUES ('Adam Lesh', 48)
INTO author (author_name, author_id) VALUES ('Adam Long', 49)
INTO author (author_name, author_id) VALUES ('Adam Mansbach', 50)
INTO author (author_name, author_id) VALUES ('Adam Mars-Jones', 51)
INTO author (author_name, author_id) VALUES ('Adam McCauley', 52)
INTO author (author_name, author_id) VALUES ('Adam Phillips', 53)
INTO author (author_name, author_id) VALUES ('Adam Rex', 54)
INTO author (author_name, author_id) VALUES ('Adam Roberts', 55)
INTO author (author_name, author_id) VALUES ('Adam Smith', 56)
INTO author (author_name, author_id) VALUES ('Adam Swift', 57)
INTO author (author_name, author_id) VALUES ('Adam Woog', 58)
INTO author (author_name, author_id) VALUES ('Adam-Troy Castro', 59)
INTO author (author_name, author_id) VALUES ('Celeste Bradley', 1165)
INTO author (author_name, author_id) VALUES ('Celeste Davidson Mannis', 1166)
INTO author (author_name, author_id) VALUES ('Cesare Beccaria', 1167)
INTO author (author_name, author_id) VALUES ('Chad Fowler', 1168)
INTO author (author_name, author_id) VALUES ('Chad Oliver', 1169)
INTO author (author_name, author_id) VALUES ('Chaim Potok', 1170)
INTO author (author_name, author_id) VALUES ('Chalmers Johnson', 1171)
INTO author (author_name, author_id) VALUES ('Chandler Brossard', 1172)
INTO author (author_name, author_id) VALUES ('Chanrithy Him', 1173)
INTO author (author_name, author_id) VALUES ('Chantal Mouffe', 1174)
INTO author (author_name, author_id) VALUES ('Chaosium Inc.', 1175)
INTO author (author_name, author_id) VALUES ('Charlaine Harris', 1176)
INTO author (author_name, author_id) VALUES ('Charlee Jacob', 1177)
INTO author (author_name, author_id) VALUES ('Charles Martin', 1178)
INTO author (author_name, author_id) VALUES ('Charles Johnson', 1179)
INTO author (author_name, author_id) VALUES ('Charles Wilson', 1180)
INTO author (author_name, author_id) VALUES ('Charles Green', 1181)
INTO author (author_name, author_id) VALUES ('Charles Lee', 1182)
INTO author (author_name, author_id) VALUES ('Charles A. Coulombe', 1183)
INTO author (author_name, author_id) VALUES ('Charles A. Peek', 1184)
INTO author (author_name, author_id) VALUES ('Charles Alexander Moore', 1185)
INTO author (author_name, author_id) VALUES ('Charles Alexander Robinson Jr.', 1186)
INTO author (author_name, author_id) VALUES ('Charles Allen', 1187)
INTO author (author_name, author_id) VALUES ('Charles Baudelaire', 1188)
INTO author (author_name, author_id) VALUES ('Charles Baxter', 1189)
INTO author (author_name, author_id) VALUES ('Charles Bowden', 1190)
INTO author (author_name, author_id) VALUES ('Charles Boyce', 1191)
INTO author (author_name, author_id) VALUES ('Charles Bukowski', 1192)
INTO author (author_name, author_id) VALUES ('Charles Burns', 1193)
INTO author (author_name, author_id) VALUES ('Charles C. Mann', 1194)
INTO author (author_name, author_id) VALUES ('Charles Coulston Gillispie', 1195)
INTO author (author_name, author_id) VALUES ('Charles Darwin', 1196)
INTO author (author_name, author_id) VALUES ('Charles de Lint', 1197)
INTO author (author_name, author_id) VALUES ('Charles Dickens', 1198)
INTO author (author_name, author_id) VALUES ('Charles E. Wilbour', 1199)
INTO author (author_name, author_id) VALUES ('Charles F. Miller', 1200)
INTO author (author_name, author_id) VALUES ('Charles Fanning', 1201)
INTO author (author_name, author_id) VALUES ('Charles Flowers', 1202)
INTO author (author_name, author_id) VALUES ('Charles Frazier', 1203)
INTO author (author_name, author_id) VALUES ('Charles G. Waugh', 1204)
INTO author (author_name, author_id) VALUES ('Charles Guignon', 1205)
INTO author (author_name, author_id) VALUES ('Charles H. Wilson', 1206)
INTO author (author_name, author_id) VALUES ('Charles Hegel', 1207)
INTO author (author_name, author_id) VALUES ('Charles Hirshberg', 1208)
INTO author (author_name, author_id) VALUES ('Charles J. Sykes', 1209)
INTO author (author_name, author_id) VALUES ('Charles John Cutcliffe Wright Hyne', 1210)
INTO author (author_name, author_id) VALUES ('Charles Johnston', 1211)
INTO author (author_name, author_id) VALUES ('Charles Keegan', 1212)
INTO author (author_name, author_id) VALUES ('Charles Kingsley', 1213)
INTO author (author_name, author_id) VALUES ('Charles Lamb', 1214)
INTO author (author_name, author_id) VALUES ('Charles Larson', 1215)
INTO author (author_name, author_id) VALUES ('Charles Lockwood', 1216)
INTO author (author_name, author_id) VALUES ('Charles M. Schulz', 1217)
INTO author (author_name, author_id) VALUES ('Charles Mackay', 1218)
INTO author (author_name, author_id) VALUES ('Charles Marowitz', 1219)
INTO author (author_name, author_id) VALUES ('Charles McKeown', 1220)
INTO author (author_name, author_id) VALUES ('Charles Moore', 1221)
INTO author (author_name, author_id) VALUES ('Charles Neider', 1222)
INTO author (author_name, author_id) VALUES ('Charles Osborne', 1223)
INTO author (author_name, author_id) VALUES ('Charles P. Rubenstein', 1224)
INTO author (author_name, author_id) VALUES ('Charles P. Zaglanis', 1225)
INTO author (author_name, author_id) VALUES ('Charles Petzold', 1226)
INTO author (author_name, author_id) VALUES ('Charles R. Forker', 1227)
INTO author (author_name, author_id) VALUES ('Charles R. Johnson', 1228)
INTO author (author_name, author_id) VALUES ('Charles R. Miller', 1229)
INTO author (author_name, author_id) VALUES ('Charles R. Smith Jr.', 1230)
INTO author (author_name, author_id) VALUES ('Charles R. Swindoll', 1231)
INTO author (author_name, author_id) VALUES ('Charles R. Walker', 1232)
INTO author (author_name, author_id) VALUES ('Charles Rembar', 1233)
INTO author (author_name, author_id) VALUES ('Charles S. Anderson Design Company', 1234)
INTO author (author_name, author_id) VALUES ('Charles Scribner Jr.', 1235)
INTO author (author_name, author_id) VALUES ('Charles Segal', 1236)
INTO author (author_name, author_id) VALUES ('Charles Seife', 1237)
INTO author (author_name, author_id) VALUES ('Charles Simic', 1238)
INTO author (author_name, author_id) VALUES ('Charles Stross', 1239)
INTO author (author_name, author_id) VALUES ('Charles Tandy', 1240)
INTO author (author_name, author_id) VALUES ('Charles Tang', 1241)
INTO author (author_name, author_id) VALUES ('Charles Taylor', 1242)
INTO author (author_name, author_id) VALUES ('Charles Todd', 1243)
INTO author (author_name, author_id) VALUES ('Charles Tomlinson', 1244)
INTO author (author_name, author_id) VALUES ('Charles Vess', 1245)
INTO author (author_name, author_id) VALUES ('Charles W. Sydnor Jr.', 1246)
INTO author (author_name, author_id) VALUES ('Charles Wheelan', 1247)
INTO author (author_name, author_id) VALUES ('Charles Willeford', 1248)
INTO author (author_name, author_id) VALUES ('Charley Boorman', 1249)
INTO author (author_name, author_id) VALUES ('Charlie Adlard', 1250)
INTO author (author_name, author_id) VALUES ('Charlie Conrad', 1251)
INTO author (author_name, author_id) VALUES ('Charlie Huston', 1252)
INTO author (author_name, author_id) VALUES ('Charlie O''Neill', 1253)
INTO author (author_name, author_id) VALUES ('Charlotte Brontë', 1254)
INTO author (author_name, author_id) VALUES ('Charlotte Fiell', 1255)
INTO author (author_name, author_id) VALUES ('Charlotte Hughes', 1256)
INTO author (author_name, author_id) VALUES ('Charlotte Lyons', 1257)
INTO author (author_name, author_id) VALUES ('Charlotte Mitchell', 1258)
INTO author (author_name, author_id) VALUES ('Charlotte Perkins Gilman', 1259)
INTO author (author_name, author_id) VALUES ('Charlton Heston', 1260)
INTO author (author_name, author_id) VALUES ('Chase Hensel', 1261)
INTO author (author_name, author_id) VALUES ('Cheri Huber', 1262)
INTO author (author_name, author_id) VALUES ('Cherry Jones', 1263)
INTO author (author_name, author_id) VALUES ('Cheryl A. Wall', 1264)
INTO author (author_name, author_id) VALUES ('Cheryl Carlson', 1265)
INTO author (author_name, author_id) VALUES ('Maurice Sendak', 5931)
INTO author (author_name, author_id) VALUES ('Mauricio Molina', 5932)
INTO author (author_name, author_id) VALUES ('Mavis Applewater', 5933)
INTO author (author_name, author_id) VALUES ('Max Allan Collins', 5934) SELECT * FROM dual;

INSERT ALL
INTO author (author_name, author_id) VALUES ('Max Barry', 5935)
INTO author (author_name, author_id) VALUES ('Max Beerbohm', 5936)
INTO author (author_name, author_id) VALUES ('Max Brod', 5937)
INTO author (author_name, author_id) VALUES ('Max Brooks', 5938)
INTO author (author_name, author_id) VALUES ('Max Eilenberg', 5939)
INTO author (author_name, author_id) VALUES ('Max Frisch', 5940)
INTO author (author_name, author_id) VALUES ('Max Lucado', 5941)
INTO author (author_name, author_id) VALUES ('Max McLean', 5942)
INTO author (author_name, author_id) VALUES ('Maxim Gorky', 5943)
INTO author (author_name, author_id) VALUES ('Maxine Clark', 5944)
INTO author (author_name, author_id) VALUES ('Maxine Hong Kingston', 5945)
INTO author (author_name, author_id) VALUES ('Maxine Kumin', 5946)
INTO author (author_name, author_id) VALUES ('Maxine Paetro', 5947)
INTO author (author_name, author_id) VALUES ('Maxine Swann', 5948)
INTO author (author_name, author_id) VALUES ('Maxwell Award', 5949)
INTO author (author_name, author_id) VALUES ('Maxwell Mackenzie', 5950)
INTO author (author_name, author_id) VALUES ('Maya Angelou', 5951)
INTO author (author_name, author_id) VALUES ('Maya Gold', 5952)
INTO author (author_name, author_id) VALUES ('Maynard F. Thomson', 5953)
INTO author (author_name, author_id) VALUES ('Mayu Shinjō', 5954)
INTO author (author_name, author_id) VALUES ('McDougal Littell', 5955)
INTO author (author_name, author_id) VALUES ('McDougal Publishing Staff', 5956)
INTO author (author_name, author_id) VALUES ('McSweeney''s Publishing', 5957)
INTO author (author_name, author_id) VALUES ('Mechtild Ciletti', 5958)
INTO author (author_name, author_id) VALUES ('Mechtild Sandberg-Ciletti', 5959)
INTO author (author_name, author_id) VALUES ('Meg Cabot', 5960)
INTO author (author_name, author_id) VALUES ('Megan Crane', 5961)
INTO author (author_name, author_id) VALUES ('Megan McCafferty', 5962)
INTO author (author_name, author_id) VALUES ('Megan McDaniel', 5963)
INTO author (author_name, author_id) VALUES ('Megan McDonald', 5964)
INTO author (author_name, author_id) VALUES ('Megan McMorris', 5965)
INTO author (author_name, author_id) VALUES ('Megan Whalen Turner', 5966)
INTO author (author_name, author_id) VALUES ('Mehmet C. Oz', 5967)
INTO author (author_name, author_id) VALUES ('Mel Bay', 5968)
INTO author (author_name, author_id) VALUES ('Mel Gilden', 5969)
INTO author (author_name, author_id) VALUES ('Mel Odom', 5970)
INTO author (author_name, author_id) VALUES ('Mel Weitsman', 5971)
INTO author (author_name, author_id) VALUES ('Mel White', 5972)
INTO author (author_name, author_id) VALUES ('Melania G. Mazzucco', 5973)
INTO author (author_name, author_id) VALUES ('Melanie Acevedo', 5974)
INTO author (author_name, author_id) VALUES ('Melanie Rawn', 5975)
INTO author (author_name, author_id) VALUES ('Melanie Tem', 5976)
INTO author (author_name, author_id) VALUES ('Melinda Curtis', 5977)
INTO author (author_name, author_id) VALUES ('Melinda Haynes', 5978)
INTO author (author_name, author_id) VALUES ('Melinda Long', 5979)
INTO author (author_name, author_id) VALUES ('Melissa de la Cruz', 5980)
INTO author (author_name, author_id) VALUES ('Melissa Kantor', 5981)
INTO author (author_name, author_id) VALUES ('Melissa Leo', 5982)
INTO author (author_name, author_id) VALUES ('Melissa M. Garcia', 5983)
INTO author (author_name, author_id) VALUES ('Melissa Painter', 5984)
INTO author (author_name, author_id) VALUES ('Melissa Senate', 5985)
INTO author (author_name, author_id) VALUES ('Melissa Sweet', 5986)
INTO author (author_name, author_id) VALUES ('Melissa Wiley', 5987)
INTO author (author_name, author_id) VALUES ('Meljean Brook', 5988)
INTO author (author_name, author_id) VALUES ('Melody Beattie', 5989)
INTO author (author_name, author_id) VALUES ('Melody Carlson', 5990)
INTO author (author_name, author_id) VALUES ('Melody Malmberg', 5991)
INTO author (author_name, author_id) VALUES ('Melvin Burgess', 5992)
INTO author (author_name, author_id) VALUES ('Melvyn Bragg', 5993)
INTO author (author_name, author_id) VALUES ('Melvyn Grant', 5994)
INTO author (author_name, author_id) VALUES ('Mercedes Lackey', 5995)
INTO author (author_name, author_id) VALUES ('Mercer Mayer', 5996)
INTO author (author_name, author_id) VALUES ('Meredith Ann Pierce', 5997)
INTO author (author_name, author_id) VALUES ('Meredith Daneman', 5998)
INTO author (author_name, author_id) VALUES ('Meredith Fletcher', 5999)
INTO author (author_name, author_id) VALUES ('Meredith Johnson', 6000)
INTO author (author_name, author_id) VALUES ('Merlin Donald', 6001)
INTO author (author_name, author_id) VALUES ('Merlin Holland', 6002)
INTO author (author_name, author_id) VALUES ('Merline Lovelace', 6003)
INTO author (author_name, author_id) VALUES ('Merrill D. Peterson', 6004)
INTO author (author_name, author_id) VALUES ('Merritt Y. Hughes', 6005)
INTO author (author_name, author_id) VALUES ('Merton M. Sealts Jr.', 6006)
INTO author (author_name, author_id) VALUES ('Mervyn Peake', 6007)
INTO author (author_name, author_id) VALUES ('Metropolitan Museum of Art', 6008)
INTO author (author_name, author_id) VALUES ('Mian Mian', 6009)
INTO author (author_name, author_id) VALUES ('Miasha', 6010)
INTO author (author_name, author_id) VALUES ('Micah Sparks', 6011)
INTO author (author_name, author_id) VALUES ('Michael Casey', 6012)
INTO author (author_name, author_id) VALUES ('Michael Lewis', 6013)
INTO author (author_name, author_id) VALUES ('Michael Ford', 6014)
INTO author (author_name, author_id) VALUES ('Michael Heath', 6015)
INTO author (author_name, author_id) VALUES ('Michael Barber', 6016)
INTO author (author_name, author_id) VALUES ('Michael Collier', 6017)
INTO author (author_name, author_id) VALUES ('Michael Lewis', 6018)
INTO author (author_name, author_id) VALUES ('Michael Williams', 6019)
INTO author (author_name, author_id) VALUES ('Michael Ayres', 6020)
INTO author (author_name, author_id) VALUES ('Michael Bass', 6021)
INTO author (author_name, author_id) VALUES ('Michael Bishop', 6022)
INTO author (author_name, author_id) VALUES ('Michael Howard', 6023)
INTO author (author_name, author_id) VALUES ('Michael Rossi', 6024)
INTO author (author_name, author_id) VALUES ('Michael Shepherd', 6025)
INTO author (author_name, author_id) VALUES ('Michael Wood', 6026)
INTO author (author_name, author_id) VALUES ('Michael A. Crom', 6027)
INTO author (author_name, author_id) VALUES ('Michael A. Stackpole', 6028)
INTO author (author_name, author_id) VALUES ('Michael Albert', 6029)
INTO author (author_name, author_id) VALUES ('Michael Armstrong', 6030)
INTO author (author_name, author_id) VALUES ('Michael Atiyeh', 6031)
INTO author (author_name, author_id) VALUES ('Michael Avi-Yonah', 6032)
INTO author (author_name, author_id) VALUES ('Michael Avon Oeming', 6033)
INTO author (author_name, author_id) VALUES ('Michael Azerrad', 6034)
INTO author (author_name, author_id) VALUES ('Michael B. Frank', 6035)
INTO author (author_name, author_id) VALUES ('Michael B. Oren', 6036)
INTO author (author_name, author_id) VALUES ('Michael Bair', 6037)
INTO author (author_name, author_id) VALUES ('Michael Bakewell', 6038)
INTO author (author_name, author_id) VALUES ('Michael Basker', 6039)
INTO author (author_name, author_id) VALUES ('Michael Baur', 6040)
INTO author (author_name, author_id) VALUES ('Michael Beck', 6041)
INTO author (author_name, author_id) VALUES ('Michael Braungart', 6042)
INTO author (author_name, author_id) VALUES ('Michael C. Feathers', 6043)
INTO author (author_name, author_id) VALUES ('Michael C.J. Putnam', 6044)
INTO author (author_name, author_id) VALUES ('Michael Cadnum', 6045)
INTO author (author_name, author_id) VALUES ('Michael Chabon', 6046)
INTO author (author_name, author_id) VALUES ('Michael Chase', 6047)
INTO author (author_name, author_id) VALUES ('Michael Clamp', 6048)
INTO author (author_name, author_id) VALUES ('Michael Connelly', 6049)
INTO author (author_name, author_id) VALUES ('Michael Corr', 6050)
INTO author (author_name, author_id) VALUES ('Michael Cox', 6051)
INTO author (author_name, author_id) VALUES ('Michael Craft', 6052)
INTO author (author_name, author_id) VALUES ('Michael Crichton', 6053)
INTO author (author_name, author_id) VALUES ('Michael Cumpsty', 6054)
INTO author (author_name, author_id) VALUES ('Michael Cunningham', 6055)
INTO author (author_name, author_id) VALUES ('Michael D. Coe', 6056)
INTO author (author_name, author_id) VALUES ('Michael D. Lyman', 6057)
INTO author (author_name, author_id) VALUES ('Michael D. Oates', 6058)
INTO author (author_name, author_id) VALUES ('Michael D''Orso', 6059)
INTO author (author_name, author_id) VALUES ('Michael David Thomas', 6060)
INTO author (author_name, author_id) VALUES ('Michael Davitt', 6061)
INTO author (author_name, author_id) VALUES ('Michael de Larrabetti', 6062)
INTO author (author_name, author_id) VALUES ('Michael Dirda', 6063)
INTO author (author_name, author_id) VALUES ('Michael Dooling', 6064)
INTO author (author_name, author_id) VALUES ('Michael Dorris', 6065)
INTO author (author_name, author_id) VALUES ('Michael E. Doyle', 6066)
INTO author (author_name, author_id) VALUES ('Michael E. Roloff', 6067)
INTO author (author_name, author_id) VALUES ('Michael E. Soulé', 6068)
INTO author (author_name, author_id) VALUES ('Michael Eliot Howard', 6069)
INTO author (author_name, author_id) VALUES ('Michael Emmerich', 6070)
INTO author (author_name, author_id) VALUES ('Michael Ende', 6071)
INTO author (author_name, author_id) VALUES ('Michael F. Roizen', 6072)
INTO author (author_name, author_id) VALUES ('Michael Feast', 6073)
INTO author (author_name, author_id) VALUES ('Michael Fiedrowicz', 6074)
INTO author (author_name, author_id) VALUES ('Michael Foreman', 6075)
INTO author (author_name, author_id) VALUES ('Michael Garland', 6076)
INTO author (author_name, author_id) VALUES ('Michael Gillespie', 6077)
INTO author (author_name, author_id) VALUES ('Michael Görden', 6078)
INTO author (author_name, author_id) VALUES ('Michael Grant', 6079)
INTO author (author_name, author_id) VALUES ('Michael Gray', 6080)
INTO author (author_name, author_id) VALUES ('Michael Grosberg', 6081)
INTO author (author_name, author_id) VALUES ('Michael H. Jackson', 6082)
INTO author (author_name, author_id) VALUES ('Michael Hague', 6083)
INTO author (author_name, author_id) VALUES ('Michael Hanlon', 6084)
INTO author (author_name, author_id) VALUES ('Michael Hardt', 6085)
INTO author (author_name, author_id) VALUES ('Michael Hauge', 6086)
INTO author (author_name, author_id) VALUES ('Michael Hemmingson', 6087)
INTO author (author_name, author_id) VALUES ('Michael Henry Heim', 6088)
INTO author (author_name, author_id) VALUES ('Michael Herr', 6089)
INTO author (author_name, author_id) VALUES ('Michael Hofmann', 6090)
INTO author (author_name, author_id) VALUES ('Michael Hordern', 6091)
INTO author (author_name, author_id) VALUES ('Michael Horowitz', 6092)
INTO author (author_name, author_id) VALUES ('Michael Hulse', 6093)
INTO author (author_name, author_id) VALUES ('Michael Hunter', 6094)
INTO author (author_name, author_id) VALUES ('Michael I. Silberkleit', 6095)
INTO author (author_name, author_id) VALUES ('Michael J. Agovino', 6096)
INTO author (author_name, author_id) VALUES ('Michael J. Bradley', 6097)
INTO author (author_name, author_id) VALUES ('Michael J. Broadway', 6098)
INTO author (author_name, author_id) VALUES ('Michael J. Davey', 6099)
INTO author (author_name, author_id) VALUES ('Michael J. DeLuca', 6100)
INTO author (author_name, author_id) VALUES ('Michael J. Gelb', 6101)
INTO author (author_name, author_id) VALUES ('Michael J. Karels', 6102)
INTO author (author_name, author_id) VALUES ('Michael J. Kiskis', 6103)
INTO author (author_name, author_id) VALUES ('Michael J. Lyons', 6104)
INTO author (author_name, author_id) VALUES ('Michael J. Mauboussin', 6105)
INTO author (author_name, author_id) VALUES ('Michael J. Nelson', 6106)
INTO author (author_name, author_id) VALUES ('Michael J. Smollin', 6107)
INTO author (author_name, author_id) VALUES ('Michael James Luzzi', 6108)
INTO author (author_name, author_id) VALUES ('Michael Jameson', 6109)
INTO author (author_name, author_id) VALUES ('Michael Jan Friedman', 6110)
INTO author (author_name, author_id) VALUES ('Michael Jasper', 6111)
INTO author (author_name, author_id) VALUES ('Michael Jecks', 6112)
INTO author (author_name, author_id) VALUES ('Michael John Petry', 6113)
INTO author (author_name, author_id) VALUES ('Michael Jordan', 6114)
INTO author (author_name, author_id) VALUES ('Michael K. Brett-Surman', 6115)
INTO author (author_name, author_id) VALUES ('Michael Kandel', 6116)
INTO author (author_name, author_id) VALUES ('Michael Karpelson', 6117)
INTO author (author_name, author_id) VALUES ('Michael Kelleher', 6118)
INTO author (author_name, author_id) VALUES ('Michael Kimmelman', 6119)
INTO author (author_name, author_id) VALUES ('Michael Korda', 6120)
INTO author (author_name, author_id) VALUES ('Michael Koryta', 6121)
INTO author (author_name, author_id) VALUES ('Michael Kreyling', 6122)
INTO author (author_name, author_id) VALUES ('Michael L. Perlis', 6123)
INTO author (author_name, author_id) VALUES ('Michael Ledwidge', 6124)
INTO author (author_name, author_id) VALUES ('Michael Littlefield', 6125)
INTO author (author_name, author_id) VALUES ('Michael Longcor', 6126)
INTO author (author_name, author_id) VALUES ('Michael Mallory', 6127)
INTO author (author_name, author_id) VALUES ('Michael Malone', 6128)
INTO author (author_name, author_id) VALUES ('Michael Marshall Smith', 6129)
INTO author (author_name, author_id) VALUES ('Michael Martchenko', 6130)
INTO author (author_name, author_id) VALUES ('Michael Mason', 6131)
INTO author (author_name, author_id) VALUES ('Michael Mazur', 6132)
INTO author (author_name, author_id) VALUES ('Michael McCurdy', 6133)
INTO author (author_name, author_id) VALUES ('Michael McMahon', 6134)
INTO author (author_name, author_id) VALUES ('Michael Moorcock', 6135)
INTO author (author_name, author_id) VALUES ('Michael Morpurgo', 6136)
INTO author (author_name, author_id) VALUES ('Michael Munn', 6137)
INTO author (author_name, author_id) VALUES ('Michael Naas', 6138)
INTO author (author_name, author_id) VALUES ('Michael Neill', 6139)
INTO author (author_name, author_id) VALUES ('Michael Nelson', 6140)
INTO author (author_name, author_id) VALUES ('Michael North', 6141)
INTO author (author_name, author_id) VALUES ('Michael O. Tunnell', 6142)
INTO author (author_name, author_id) VALUES ('Michael Ochs', 6143)
INTO author (author_name, author_id) VALUES ('Michael Ondaatje', 6144)
INTO author (author_name, author_id) VALUES ('Michael Page', 6145)
INTO author (author_name, author_id) VALUES ('Michael Pagel', 6146)
INTO author (author_name, author_id) VALUES ('Michael Palin', 6147)
INTO author (author_name, author_id) VALUES ('Michael Palmer', 6148)
INTO author (author_name, author_id) VALUES ('Michael Parenti', 6149)
INTO author (author_name, author_id) VALUES ('Michael Parfit', 6150)
INTO author (author_name, author_id) VALUES ('Michael Patrick Hearn', 6151)
INTO author (author_name, author_id) VALUES ('Michael Pollan', 6152)
INTO author (author_name, author_id) VALUES ('Michael Prichard', 6153)
INTO author (author_name, author_id) VALUES ('Michael R. Meyer', 6154)
INTO author (author_name, author_id) VALUES ('Michael R. French', 6155)
INTO author (author_name, author_id) VALUES ('Michael R. Phillips', 6156)
INTO author (author_name, author_id) VALUES ('Michael Rabiger', 6157)
INTO author (author_name, author_id) VALUES ('Michael Reaves', 6158)
INTO author (author_name, author_id) VALUES ('Michael Ruse', 6159)
INTO author (author_name, author_id) VALUES ('Michael S. Smith', 6160)
INTO author (author_name, author_id) VALUES ('Michael S. Berliner', 6161)
INTO author (author_name, author_id) VALUES ('Michael S. Horton', 6162)
INTO author (author_name, author_id) VALUES ('Michael S. Lasky', 6163)
INTO author (author_name, author_id) VALUES ('Michael S. Reynolds', 6164)
INTO author (author_name, author_id) VALUES ('Michael Scammell', 6165)
INTO author (author_name, author_id) VALUES ('Michael Shaara', 6166)
INTO author (author_name, author_id) VALUES ('Michael Sheen', 6167)
INTO author (author_name, author_id) VALUES ('Michael Shinagel', 6168)
INTO author (author_name, author_id) VALUES ('Michael Slater', 6169)
INTO author (author_name, author_id) VALUES ('Michael Spring', 6170)
INTO author (author_name, author_id) VALUES ('Michael Streissguth', 6171)
INTO author (author_name, author_id) VALUES ('Michael Sutfin', 6172)
INTO author (author_name, author_id) VALUES ('Michael Swanwick', 6173)
INTO author (author_name, author_id) VALUES ('Michael Syvanen', 6174)
INTO author (author_name, author_id) VALUES ('Michael T. Ghiselin', 6175)
INTO author (author_name, author_id) VALUES ('Michael T. Goodrich', 6176)
INTO author (author_name, author_id) VALUES ('Michael T. Smith', 6177)
INTO author (author_name, author_id) VALUES ('Michael Tanner', 6178)
INTO author (author_name, author_id) VALUES ('Michael Teitelbaum', 6179)
INTO author (author_name, author_id) VALUES ('Michael Vitez', 6180)
INTO author (author_name, author_id) VALUES ('Michael W. Dean', 6181)
INTO author (author_name, author_id) VALUES ('Michael W. Jennings', 6182)
INTO author (author_name, author_id) VALUES ('Michael Walzer', 6183)
INTO author (author_name, author_id) VALUES ('Michael Warner', 6184)
INTO author (author_name, author_id) VALUES ('Michael Wharton', 6185)
INTO author (author_name, author_id) VALUES ('Michael Winterbottom', 6186)
INTO author (author_name, author_id) VALUES ('Michael Wm. Kaluta', 6187)
INTO author (author_name, author_id) VALUES ('Michael York', 6188)
INTO author (author_name, author_id) VALUES ('Michael Z. Williamson', 6189)
INTO author (author_name, author_id) VALUES ('Michael Zulli', 6190)
INTO author (author_name, author_id) VALUES ('Michaela Muntean', 6191)
INTO author (author_name, author_id) VALUES ('Michale W. Perry', 6192)
INTO author (author_name, author_id) VALUES ('Michel Courtois-Fourcy', 6193)
INTO author (author_name, author_id) VALUES ('Michel de Montaigne', 6194)
INTO author (author_name, author_id) VALUES ('Michel Etienne', 6195)
INTO author (author_name, author_id) VALUES ('Michel Faber', 6196)
INTO author (author_name, author_id) VALUES ('Michel Foucault', 6197)
INTO author (author_name, author_id) VALUES ('Michel Lacombe', 6198)
INTO author (author_name, author_id) VALUES ('Michela Wrong', 6199)
INTO author (author_name, author_id) VALUES ('Michèle Barrett', 6200)
INTO author (author_name, author_id) VALUES ('Michele K. Spike', 6201)
INTO author (author_name, author_id) VALUES ('Michèle Roberts', 6202)
INTO author (author_name, author_id) VALUES ('Michele Wrightson', 6203)
INTO author (author_name, author_id) VALUES ('Michelle Feynman', 6204)
INTO author (author_name, author_id) VALUES ('Michelle Herpe-Volinsky', 6205)
INTO author (author_name, author_id) VALUES ('Michelle Lovric', 6206)
INTO author (author_name, author_id) VALUES ('Michelle Madsen', 6207)
INTO author (author_name, author_id) VALUES ('Michelle Sagara', 6208)
INTO author (author_name, author_id) VALUES ('Michelle Sagara West', 6209)
INTO author (author_name, author_id) VALUES ('Michelle Tea', 6210)
INTO author (author_name, author_id) VALUES ('Michiko Hiraoka', 6211)
INTO author (author_name, author_id) VALUES ('Michio Kaku', 6212)
INTO author (author_name, author_id) VALUES ('Michio Kushi', 6213)
INTO author (author_name, author_id) VALUES ('Michka Assayas', 6214)
INTO author (author_name, author_id) VALUES ('Mick Gray', 6215)
INTO author (author_name, author_id) VALUES ('Mick Mars', 6216)
INTO author (author_name, author_id) VALUES ('Mick O''Hare', 6217)
INTO author (author_name, author_id) VALUES ('Mick Rock', 6218)
INTO author (author_name, author_id) VALUES ('Mick Wiggins', 6219)
INTO author (author_name, author_id) VALUES ('Mickey Zucker Reichert', 6220)
INTO author (author_name, author_id) VALUES ('Micol Ostow', 6221)
INTO author (author_name, author_id) VALUES ('Middlesex Borough Heritage Committee', 6222)
INTO author (author_name, author_id) VALUES ('Miep Gies', 6223)
INTO author (author_name, author_id) VALUES ('Miguel de Cervantes Saavedra', 6224)
INTO author (author_name, author_id) VALUES ('Miguel López-Remiro', 6225)
INTO author (author_name, author_id) VALUES ('Miguel Marias', 6226)
INTO author (author_name, author_id) VALUES ('Miguel Martínez Sarmiento', 6227)
INTO author (author_name, author_id) VALUES ('Miguel Mora', 6228)
INTO author (author_name, author_id) VALUES ('Miguel Sáenz', 6229)
INTO author (author_name, author_id) VALUES ('Miguel Serrano', 6230)
INTO author (author_name, author_id) VALUES ('Mikal Gilmore', 6231)
INTO author (author_name, author_id) VALUES ('Mikal Trimm', 6232)
INTO author (author_name, author_id) VALUES ('Mike Mason', 6233)
INTO author (author_name, author_id) VALUES ('Mike Davis', 6234)
INTO author (author_name, author_id) VALUES ('Mike Rowe', 6235)
INTO author (author_name, author_id) VALUES ('Mike Allred', 6236)
INTO author (author_name, author_id) VALUES ('Mike Ashley', 6237)
INTO author (author_name, author_id) VALUES ('Mike Byrne', 6238)
INTO author (author_name, author_id) VALUES ('Mike Carey', 6239)
INTO author (author_name, author_id) VALUES ('Mike Caro', 6240)
INTO author (author_name, author_id) VALUES ('Mike Clark', 6241)
INTO author (author_name, author_id) VALUES ('Mike Clelland', 6242)
INTO author (author_name, author_id) VALUES ('Mike Crowell', 6243)
INTO author (author_name, author_id) VALUES ('Mike Deodato', 6244)
INTO author (author_name, author_id) VALUES ('Mike Dringenberg', 6245)
INTO author (author_name, author_id) VALUES ('Mike Flaherty', 6246)
INTO author (author_name, author_id) VALUES ('Mike Kennedy', 6247)
INTO author (author_name, author_id) VALUES ('Mike Lupica', 6248)
INTO author (author_name, author_id) VALUES ('Mike Mason', 6249)
INTO author (author_name, author_id) VALUES ('Mike Mignola', 6250)
INTO author (author_name, author_id) VALUES ('Mike Ploog', 6251)
INTO author (author_name, author_id) VALUES ('Mike Resnick', 6252)
INTO author (author_name, author_id) VALUES ('Mike S. Miller', 6253)
INTO author (author_name, author_id) VALUES ('Mike Turner', 6254)
INTO author (author_name, author_id) VALUES ('Mike Wieringo', 6255)
INTO author (author_name, author_id) VALUES ('Mikhail Bakhtin', 6256)
INTO author (author_name, author_id) VALUES ('Mikhail Bakunin', 6257)
INTO author (author_name, author_id) VALUES ('Mikhail Bulgakov', 6258)
INTO author (author_name, author_id) VALUES ('Mikhail Tal', 6259)
INTO author (author_name, author_id) VALUES ('Milan Kundera', 6260)
INTO author (author_name, author_id) VALUES ('Milan Trenc', 6261)
INTO author (author_name, author_id) VALUES ('Mildred Benson', 6262)
INTO author (author_name, author_id) VALUES ('Miles J. Stanford', 6263)
INTO author (author_name, author_id) VALUES ('Miles Thompson', 6264)
INTO author (author_name, author_id) VALUES ('Milo Winter', 6265)
INTO author (author_name, author_id) VALUES ('Milton Rugoff', 6266)
INTO author (author_name, author_id) VALUES ('Mimi Dietrich', 6267)
INTO author (author_name, author_id) VALUES ('Mina Loy', 6268)
INTO author (author_name, author_id) VALUES ('Mine Yoshizaki', 6269)
INTO author (author_name, author_id) VALUES ('Mineko Iwasaki', 6270)
INTO author (author_name, author_id) VALUES ('Minette Walters', 6271)
INTO author (author_name, author_id) VALUES ('Minfong Ho', 6272)
INTO author (author_name, author_id) VALUES ('Mira Nair', 6273)
INTO author (author_name, author_id) VALUES ('Mircea Eliade', 6274)
INTO author (author_name, author_id) VALUES ('Miriam Toews', 6275)
INTO author (author_name, author_id) VALUES ('Mirjana Cvekić', 6276)
INTO author (author_name, author_id) VALUES ('Miron Borysenko', 6277)
INTO author (author_name, author_id) VALUES ('Miroslav Sasek', 6278)
INTO author (author_name, author_id) VALUES ('Miroslav Volf', 6279)
INTO author (author_name, author_id) VALUES ('Misao Inagaki', 6280)
INTO author (author_name, author_id) VALUES ('Miska Petersham', 6281)
INTO author (author_name, author_id) VALUES ('Mistress Lorelei', 6282)
INTO author (author_name, author_id) VALUES ('Misty Hook', 6283)
INTO author (author_name, author_id) VALUES ('Mitali Perkins', 6284)
INTO author (author_name, author_id) VALUES ('Mitch Albom', 6285)
INTO author (author_name, author_id) VALUES ('Mitch Ginsburg', 6286)
INTO author (author_name, author_id) VALUES ('Mitchel Resnick', 6287)
INTO author (author_name, author_id) VALUES ('Mitchell Alexander Leaska', 6288)
INTO author (author_name, author_id) VALUES ('Mitchell Gaynor', 6289)
INTO author (author_name, author_id) VALUES ('Mitchell Sharmat', 6290)
INTO author (author_name, author_id) VALUES ('Miyamoto Musashi', 6291)
INTO author (author_name, author_id) VALUES ('Mœbius', 6292)
INTO author (author_name, author_id) VALUES ('Mollie Hunter', 6293)
INTO author (author_name, author_id) VALUES ('Molly Bang', 6294)
INTO author (author_name, author_id) VALUES ('Molly Brown', 6295)
INTO author (author_name, author_id) VALUES ('Molly C. Lee', 6296)
INTO author (author_name, author_id) VALUES ('Molly E. Holzschlag', 6297)
INTO author (author_name, author_id) VALUES ('Molly Hatchet', 6298)
INTO author (author_name, author_id) VALUES ('Molly Mason', 6299)
INTO author (author_name, author_id) VALUES ('Molly Mia Stewart', 6300)
INTO author (author_name, author_id) VALUES ('Molyn Leszcz', 6301)
INTO author (author_name, author_id) VALUES ('Mona Lisa Schulz', 6302)
INTO author (author_name, author_id) VALUES ('Mona Mulhair', 6303)
INTO author (author_name, author_id) VALUES ('Monica Ali', 6304)
INTO author (author_name, author_id) VALUES ('Monica Drake', 6305)
INTO author (author_name, author_id) VALUES ('Monica Furlong', 6306)
INTO author (author_name, author_id) VALUES ('Monica Gesue', 6307)
INTO author (author_name, author_id) VALUES ('Monica Jackson', 6308)
INTO author (author_name, author_id) VALUES ('Monica Kulling', 6309)
INTO author (author_name, author_id) VALUES ('Monique Fong Wust', 6310)
INTO author (author_name, author_id) VALUES ('Monique Truong', 6311)
INTO author (author_name, author_id) VALUES ('Monte Cook', 6312)
INTO author (author_name, author_id) VALUES ('Monty Roberts', 6313)
INTO author (author_name, author_id) VALUES ('Moonshine', 6314)
INTO author (author_name, author_id) VALUES ('Morag McKendrick Pippin', 6315)
INTO author (author_name, author_id) VALUES ('Morag Prunty', 6316)
INTO author (author_name, author_id) VALUES ('Morgan Hawke', 6317)
INTO author (author_name, author_id) VALUES ('Morgan Leigh', 6318)
INTO author (author_name, author_id) VALUES ('Morton Dauwen Zabel', 6319)
INTO author (author_name, author_id) VALUES ('Moses Hadas', 6320)
INTO author (author_name, author_id) VALUES ('Moura Budberg', 6321)
INTO author (author_name, author_id) VALUES ('Muhammad Yunus', 6322)
INTO author (author_name, author_id) VALUES ('Mulk Raj Anand', 6323)
INTO author (author_name, author_id) VALUES ('Murasaki Shikibu', 6324)
INTO author (author_name, author_id) VALUES ('Muriel Rukeyser', 6325)
INTO author (author_name, author_id) VALUES ('Muriel Spark', 6326)
INTO author (author_name, author_id) VALUES ('Murray Kempton', 6327)
INTO author (author_name, author_id) VALUES ('Murray Sayle', 6328)
INTO author (author_name, author_id) VALUES ('Murray Smith', 6329)
INTO author (author_name, author_id) VALUES ('Myla Goldberg', 6330)
INTO author (author_name, author_id) VALUES ('Myles Burnyeat', 6331)
INTO author (author_name, author_id) VALUES ('Mymi Doinet', 6332)
INTO author (author_name, author_id) VALUES ('Myra Jehlen', 6333)
INTO author (author_name, author_id) VALUES ('Mystery', 6334)
INTO author (author_name, author_id) VALUES ('N. Mark Collins', 6335)
INTO author (author_name, author_id) VALUES ('N.C. Wyeth', 6336)
INTO author (author_name, author_id) VALUES ('N.K. Sandars', 6337)
INTO author (author_name, author_id) VALUES ('Nabum N. Glazer', 6338)
INTO author (author_name, author_id) VALUES ('Nadeem Aslam', 6339)
INTO author (author_name, author_id) VALUES ('Nadeem Zaidi', 6340)
INTO author (author_name, author_id) VALUES ('Nadia May', 6341)
INTO author (author_name, author_id) VALUES ('Nadine Cohodas', 6342)
INTO author (author_name, author_id) VALUES ('Nadine Epstein', 6343)
INTO author (author_name, author_id) VALUES ('Nāgārjuna', 6344)
INTO author (author_name, author_id) VALUES ('Naguib Mahfouz', 6345)
INTO author (author_name, author_id) VALUES ('Nahum N. Glatzer', 6346)
INTO author (author_name, author_id) VALUES ('Nanao Saikawa', 6347)
INTO author (author_name, author_id) VALUES ('Nancy Harding', 6348)
INTO author (author_name, author_id) VALUES ('Nancy Asire', 6349)
INTO author (author_name, author_id) VALUES ('Nancy Bartholomew', 6350)
INTO author (author_name, author_id) VALUES ('Nancy Bond', 6351)
INTO author (author_name, author_id) VALUES ('Nancy Conrad', 6352)
INTO author (author_name, author_id) VALUES ('Nancy Cote', 6353)
INTO author (author_name, author_id) VALUES ('Nancy Ekholm Burkert', 6354)
INTO author (author_name, author_id) VALUES ('Nancy Farmer', 6355)
INTO author (author_name, author_id) VALUES ('Nancy Friday', 6356)
INTO author (author_name, author_id) VALUES ('Nancy Hall', 6357)
INTO author (author_name, author_id) VALUES ('Nancy Harrison', 6358)
INTO author (author_name, author_id) VALUES ('Nancy Holyoke', 6359)
INTO author (author_name, author_id) VALUES ('Nancy Ireson', 6360)
INTO author (author_name, author_id) VALUES ('Nancy J. Smith', 6361)
INTO author (author_name, author_id) VALUES ('Nancy L. Mace', 6362)
INTO author (author_name, author_id) VALUES ('Nancy M. Armstrong', 6363)
INTO author (author_name, author_id) VALUES ('Nancy M. Leak', 6364)
INTO author (author_name, author_id) VALUES ('Nancy MacDonell', 6365)
INTO author (author_name, author_id) VALUES ('Nancy MacDonell Smith', 6366)
INTO author (author_name, author_id) VALUES ('Nancy Milford', 6367)
INTO author (author_name, author_id) VALUES ('Nancy Osa', 6368)
INTO author (author_name, author_id) VALUES ('Nancy Pickard', 6369)
INTO author (author_name, author_id) VALUES ('Nancy Seligsohn', 6370)
INTO author (author_name, author_id) VALUES ('Nancy Sheehan', 6371)
INTO author (author_name, author_id) VALUES ('Nancy Springer', 6372)
INTO author (author_name, author_id) VALUES ('Nancy Tillman', 6373)
INTO author (author_name, author_id) VALUES ('Nancy Varian Berberick', 6374)
INTO author (author_name, author_id) VALUES ('Nancy Verde Barr', 6375)
INTO author (author_name, author_id) VALUES ('Nancy Virginia Varian', 6376)
INTO author (author_name, author_id) VALUES ('Nancy White Carlstrom', 6377)
INTO author (author_name, author_id) VALUES ('Susan Bernofsky', 8370)
INTO author (author_name, author_id) VALUES ('Susan Carroll', 8371)
INTO author (author_name, author_id) VALUES ('Susan Conant', 8372)
INTO author (author_name, author_id) VALUES ('Susan Cooper', 8373)
INTO author (author_name, author_id) VALUES ('Susan Dick', 8374)
INTO author (author_name, author_id) VALUES ('Susan Donovan', 8375)
INTO author (author_name, author_id) VALUES ('Susan Dunlap', 8376)
INTO author (author_name, author_id) VALUES ('Susan Dunn', 8377)
INTO author (author_name, author_id) VALUES ('Susan Forward', 8378)
INTO author (author_name, author_id) VALUES ('Susan Grant', 8379)
INTO author (author_name, author_id) VALUES ('Susan Gubar', 8380)
INTO author (author_name, author_id) VALUES ('Susan Hill', 8381)
INTO author (author_name, author_id) VALUES ('Susan Howatch', 8382)
INTO author (author_name, author_id) VALUES ('Susan J. Wolfson', 8383)
INTO author (author_name, author_id) VALUES ('Susan Jeffers', 8384)
INTO author (author_name, author_id) VALUES ('Susan K. Harris', 8385)
INTO author (author_name, author_id) VALUES ('Susan Kandel', 8386)
INTO author (author_name, author_id) VALUES ('Susan Krinard', 8387)
INTO author (author_name, author_id) VALUES ('Susan Minot', 8388)
INTO author (author_name, author_id) VALUES ('Susan Moller Okin', 8389)
INTO author (author_name, author_id) VALUES ('Susan Nanus', 8390)
INTO author (author_name, author_id) VALUES ('Susan O''Malley', 8391)
INTO author (author_name, author_id) VALUES ('Susan Oliver', 8392)
INTO author (author_name, author_id) VALUES ('Susan Palwick', 8393)
INTO author (author_name, author_id) VALUES ('Susan R. Wolf', 8394)
INTO author (author_name, author_id) VALUES ('Susan Ring', 8395)
INTO author (author_name, author_id) VALUES ('Susan Shillinglaw', 8396)
INTO author (author_name, author_id) VALUES ('Susan Sizemore', 8397)
INTO author (author_name, author_id) VALUES ('Susan Snyder', 8398)
INTO author (author_name, author_id) VALUES ('Susan Sontag', 8399)
INTO author (author_name, author_id) VALUES ('Susan Squires', 8400)
INTO author (author_name, author_id) VALUES ('Susan Swan', 8401)
INTO author (author_name, author_id) VALUES ('Susan Van Kirk', 8402)
INTO author (author_name, author_id) VALUES ('Susanna B. Hecht', 8403)
INTO author (author_name, author_id) VALUES ('Susanna Basso', 8404)
INTO author (author_name, author_id) VALUES ('Susanna Carr', 8405)
INTO author (author_name, author_id) VALUES ('Susanna Clarke', 8406)
INTO author (author_name, author_id) VALUES ('Susanna Kaysen', 8407)
INTO author (author_name, author_id) VALUES ('Susanna Tamaro', 8408)
INTO author (author_name, author_id) VALUES ('Susanne Althoetmar-Smarczyk', 8409)
INTO author (author_name, author_id) VALUES ('Susanne Kuhlmann-Krieg', 8410)
INTO author (author_name, author_id) VALUES ('Susanne Woods', 8411)
INTO author (author_name, author_id) VALUES ('Susie Conklin', 8412)
INTO author (author_name, author_id) VALUES ('Susumu Yamaguchi', 8413)
INTO author (author_name, author_id) VALUES ('Suzanne Arms', 8414)
INTO author (author_name, author_id) VALUES ('Suzanne B. Falck-Yi', 8415)
INTO author (author_name, author_id) VALUES ('Suzanne C. O''Connell Smeltzer', 8416)
INTO author (author_name, author_id) VALUES ('Suzanne Chisholm', 8417)
INTO author (author_name, author_id) VALUES ('Suzanne Enoch', 8418)
INTO author (author_name, author_id) VALUES ('Suzanne Farrell', 8419)
INTO author (author_name, author_id) VALUES ('Suzanne Higgins', 8420)
INTO author (author_name, author_id) VALUES ('Suzanne Jill Levine', 8421)
INTO author (author_name, author_id) VALUES ('Suzanne Keen', 8422)
INTO author (author_name, author_id) VALUES ('Suzanne Kleid', 8423)
INTO author (author_name, author_id) VALUES ('Suzanne Macpherson', 8424)
INTO author (author_name, author_id) VALUES ('Suzanne Rappaport', 8425)
INTO author (author_name, author_id) VALUES ('Suzanne Sale', 8426)
INTO author (author_name, author_id) VALUES ('Suzette Haden Elgin', 8427)
INTO author (author_name, author_id) VALUES ('Sven Birkerts', 8428)
INTO author (author_name, author_id) VALUES ('Sven Regener', 8429)
INTO author (author_name, author_id) VALUES ('Sverre Lyngstad', 8430)
INTO author (author_name, author_id) VALUES ('Swain Wódening', 8431)
INTO author (author_name, author_id) VALUES ('Swami Vivekananda', 8432)
INTO author (author_name, author_id) VALUES ('Sy Montgomery', 8433)
INTO author (author_name, author_id) VALUES ('Syd Hoff', 8434)
INTO author (author_name, author_id) VALUES ('Sydney Taylor', 8435)
INTO author (author_name, author_id) VALUES ('Sylvère Lotringer', 8436)
INTO author (author_name, author_id) VALUES ('Sylvester Stallone', 8437)
INTO author (author_name, author_id) VALUES ('Sylvia Browne', 8438)
INTO author (author_name, author_id) VALUES ('Sylvia Cassedy', 8439)
INTO author (author_name, author_id) VALUES ('Sylvia Day', 8440)
INTO author (author_name, author_id) VALUES ('Sylvia Engdahl', 8441)
INTO author (author_name, author_id) VALUES ('Sylvia Long', 8442)
INTO author (author_name, author_id) VALUES ('Sylvia Nasar', 8443)
INTO author (author_name, author_id) VALUES ('Sylvia Plath', 8444)
INTO author (author_name, author_id) VALUES ('Sylvia Townsend Warner', 8445)
INTO author (author_name, author_id) VALUES ('Sylvie Durastanti', 8446)
INTO author (author_name, author_id) VALUES ('Sylvie Le Bon de Beauvoir', 8447)
INTO author (author_name, author_id) VALUES ('T. Coraghessan Boyle', 8448)
INTO author (author_name, author_id) VALUES ('T. Taylor Bruce', 8449)
INTO author (author_name, author_id) VALUES ('T.A. Barron', 8450)
INTO author (author_name, author_id) VALUES ('T.B. Bottomore', 8451)
INTO author (author_name, author_id) VALUES ('T.H. Watkins', 8452)
INTO author (author_name, author_id) VALUES ('T.H. White', 8453)
INTO author (author_name, author_id) VALUES ('T.J. Reed', 8454)
INTO author (author_name, author_id) VALUES ('T.J. Wylie', 8455)
INTO author (author_name, author_id) VALUES ('T.L. Lowery', 8456)
INTO author (author_name, author_id) VALUES ('T.R. Reid', 8457)
INTO author (author_name, author_id) VALUES ('T.S. Eliot', 8458)
INTO author (author_name, author_id) VALUES ('T.Z. Lavine', 8459)
INTO author (author_name, author_id) VALUES ('Tacitus', 8460)
INTO author (author_name, author_id) VALUES ('Tad Williams', 8461)
INTO author (author_name, author_id) VALUES ('Tagreid Abu-Hassabo', 8462)
INTO author (author_name, author_id) VALUES ('Takashi Hashiguchi', 8463)
INTO author (author_name, author_id) VALUES ('Takehiko Inoue', 8464)
INTO author (author_name, author_id) VALUES ('Takeshi Obata', 8465)
INTO author (author_name, author_id) VALUES ('Tallulah Bankhead', 8466)
INTO author (author_name, author_id) VALUES ('Tamara Thorne', 8467)
INTO author (author_name, author_id) VALUES ('Tamora Pierce', 8468)
INTO author (author_name, author_id) VALUES ('Tan Lin', 8469)
INTO author (author_name, author_id) VALUES ('Tananarive Due', 8470)
INTO author (author_name, author_id) VALUES ('Tania Stern', 8471)
INTO author (author_name, author_id) VALUES ('Tania Zamorsky', 8472)
INTO author (author_name, author_id) VALUES ('Tanith Lee', 8473)
INTO author (author_name, author_id) VALUES ('Tantoo Cardinal', 8474)
INTO author (author_name, author_id) VALUES ('Tanuja Desai Hidier', 8475)
INTO author (author_name, author_id) VALUES ('Tanya Bastianich Manuali', 8476)
INTO author (author_name, author_id) VALUES ('Tanya Huff', 8477)
INTO author (author_name, author_id) VALUES ('Tanya Remer Altmann', 8478)
INTO author (author_name, author_id) VALUES ('Tara McPherson', 8479)
INTO author (author_name, author_id) VALUES ('Tara MacCarthy', 8480)
INTO author (author_name, author_id) VALUES ('Tara McCarthy', 8481)
INTO author (author_name, author_id) VALUES ('Tasha Tudor', 8482)
INTO author (author_name, author_id) VALUES ('Taylan Taftaf', 8483)
INTO author (author_name, author_id) VALUES ('Ted Bader', 8484)
INTO author (author_name, author_id) VALUES ('Ted Bell', 8485)
INTO author (author_name, author_id) VALUES ('Tim R. Swartz', 8646)
INTO author (author_name, author_id) VALUES ('Tim Robbins', 8647)
INTO author (author_name, author_id) VALUES ('Tim Turner', 8648)
INTO author (author_name, author_id) VALUES ('Tim Underwood', 8649)
INTO author (author_name, author_id) VALUES ('Tim Woods', 8650)
INTO author (author_name, author_id) VALUES ('Time-Life Books', 8651)
INTO author (author_name, author_id) VALUES ('Timothy Taylor', 8652)
INTO author (author_name, author_id) VALUES ('Timothy B. Tyson', 8653)
INTO author (author_name, author_id) VALUES ('Timothy Basil Ering', 8654)
INTO author (author_name, author_id) VALUES ('Timothy D. Taylor', 8655)
INTO author (author_name, author_id) VALUES ('Timothy D. Wilson', 8656)
INTO author (author_name, author_id) VALUES ('Timothy Ferris', 8657)
INTO author (author_name, author_id) VALUES ('Timothy Findley', 8658)
INTO author (author_name, author_id) VALUES ('Timothy McDermott', 8659)
INTO author (author_name, author_id) VALUES ('Timothy Meis', 8660)
INTO author (author_name, author_id) VALUES ('Timothy Moriarty', 8661)
INTO author (author_name, author_id) VALUES ('Timothy S. Murphy', 8662)
INTO author (author_name, author_id) VALUES ('Timothy Truman', 8663)
INTO author (author_name, author_id) VALUES ('Timothy Zahn', 8664)
INTO author (author_name, author_id) VALUES ('Tina Blythe', 8665)
INTO author (author_name, author_id) VALUES ('Tina Hannan', 8666)
INTO author (author_name, author_id) VALUES ('Tirso de Molina', 8667)
INTO author (author_name, author_id) VALUES ('Tish Boyle', 8668)
INTO author (author_name, author_id) VALUES ('Tite Kubo', 8669)
INTO author (author_name, author_id) VALUES ('Tobias Churton', 8670)
INTO author (author_name, author_id) VALUES ('Tobias Grace', 8671)
INTO author (author_name, author_id) VALUES ('Tobias Smollett', 8672)
INTO author (author_name, author_id) VALUES ('Tobias Wolff', 8673)
INTO author (author_name, author_id) VALUES ('Tobin Larson', 8674)
INTO author (author_name, author_id) VALUES ('Toby Litt', 8675)
INTO author (author_name, author_id) VALUES ('Todd Davis', 8676)
INTO author (author_name, author_id) VALUES ('Todd Field', 8677)
INTO author (author_name, author_id) VALUES ('Todd Gitlin', 8678)
INTO author (author_name, author_id) VALUES ('Todd Green', 8679)
INTO author (author_name, author_id) VALUES ('Todd Hanson', 8680)
INTO author (author_name, author_id) VALUES ('Todd Klein', 8681)
INTO author (author_name, author_id) VALUES ('Todd McCaffrey', 8682)
INTO author (author_name, author_id) VALUES ('Todd Telander', 8683)
INTO author (author_name, author_id) VALUES ('Todd W.', 8684)
INTO author (author_name, author_id) VALUES ('Todd W. Hall', 8685)
INTO author (author_name, author_id) VALUES ('Tom Arnett', 8686)
INTO author (author_name, author_id) VALUES ('Tom Beck', 8687)
INTO author (author_name, author_id) VALUES ('Tom Bissell', 8688)
INTO author (author_name, author_id) VALUES ('Tom Brevoort', 8689)
INTO author (author_name, author_id) VALUES ('Tom Brokaw', 8690)
INTO author (author_name, author_id) VALUES ('Tom Carpenter', 8691)
INTO author (author_name, author_id) VALUES ('Tom Clancy', 8692)
INTO author (author_name, author_id) VALUES ('Tom D. Crouch', 8693)
INTO author (author_name, author_id) VALUES ('Tom DeFalco', 8694)
INTO author (author_name, author_id) VALUES ('Tom Derenick', 8695)
INTO author (author_name, author_id) VALUES ('Tom Ford', 8696)
INTO author (author_name, author_id) VALUES ('Tom Fowler', 8697)
INTO author (author_name, author_id) VALUES ('Tom Gralish', 8698)
INTO author (author_name, author_id) VALUES ('Tom Griffith', 8699)
INTO author (author_name, author_id) VALUES ('Tom Hart', 8700)
INTO author (author_name, author_id) VALUES ('Tom Hiney', 8701)
INTO author (author_name, author_id) VALUES ('Tom Hodges', 8702)
INTO author (author_name, author_id) VALUES ('Tom Hodgkinson', 8703)
INTO author (author_name, author_id) VALUES ('Tom Humphries', 8704)
INTO author (author_name, author_id) VALUES ('Tom Hunt', 8705)
INTO author (author_name, author_id) VALUES ('Tom Hunter', 8706)
INTO author (author_name, author_id) VALUES ('Tom Kelley', 8707)
INTO author (author_name, author_id) VALUES ('Tom Lichtenheld', 8708)
INTO author (author_name, author_id) VALUES ('Tom Masters', 8709)
INTO author (author_name, author_id) VALUES ('Tom McGregor', 8710)
INTO author (author_name, author_id) VALUES ('Tom Morris', 8711)
INTO author (author_name, author_id) VALUES ('Tom Nguyen', 8712)
INTO author (author_name, author_id) VALUES ('Tom Osborne', 8713)
INTO author (author_name, author_id) VALUES ('Tom Paine', 8714)
INTO author (author_name, author_id) VALUES ('Tom Perrotta', 8715)
INTO author (author_name, author_id) VALUES ('Tom Peters', 8716)
INTO author (author_name, author_id) VALUES ('Tom Piccirilli', 8717)
INTO author (author_name, author_id) VALUES ('Tom Raney', 8718)
INTO author (author_name, author_id) VALUES ('Tom Robbins', 8719)
INTO author (author_name, author_id) VALUES ('Tom Sellwood', 8720)
INTO author (author_name, author_id) VALUES ('Tom Shippey', 8721)
INTO author (author_name, author_id) VALUES ('Tom Standage', 8722)
INTO author (author_name, author_id) VALUES ('Tom Stanton', 8723)
INTO author (author_name, author_id) VALUES ('Tom Stoppard', 8724)
INTO author (author_name, author_id) VALUES ('Tom Teicholz', 8725)
INTO author (author_name, author_id) VALUES ('Tom Wicker', 8726)
INTO author (author_name, author_id) VALUES ('Tom Wolfe', 8727)
INTO author (author_name, author_id) VALUES ('Tomie dePaola', 8728)
INTO author (author_name, author_id) VALUES ('Tommy Lee', 8729)
INTO author (author_name, author_id) VALUES ('Tommy Lee Edwards', 8730)
INTO author (author_name, author_id) VALUES ('Tomo Kimura', 8731)
INTO author (author_name, author_id) VALUES ('Tomo Matsumoto', 8732)
INTO author (author_name, author_id) VALUES ('Toni Bentley', 8733)
INTO author (author_name, author_id) VALUES ('Toni Morrison', 8734)
INTO author (author_name, author_id) VALUES ('Tony Roberts', 8735)
INTO author (author_name, author_id) VALUES ('Tony Langham', 8736)
INTO author (author_name, author_id) VALUES ('Tony Akins', 8737)
INTO author (author_name, author_id) VALUES ('Tony Ballantyne', 8738)
INTO author (author_name, author_id) VALUES ('Tony DiTerlizzi', 8739)
INTO author (author_name, author_id) VALUES ('Tony Goldwyn', 8740)
INTO author (author_name, author_id) VALUES ('Tony Harris', 8741)
INTO author (author_name, author_id) VALUES ('Tony Hawks', 8742)
INTO author (author_name, author_id) VALUES ('Tony Horwitz', 8743)
INTO author (author_name, author_id) VALUES ('Tony Judt', 8744)
INTO author (author_name, author_id) VALUES ('Tony Kushner', 8745)
INTO author (author_name, author_id) VALUES ('Tony Moore', 8746)
INTO author (author_name, author_id) VALUES ('Tony Ring', 8747)
INTO author (author_name, author_id) VALUES ('Tony Ross', 8748)
INTO author (author_name, author_id) VALUES ('Tony Schwartz', 8749)
INTO author (author_name, author_id) VALUES ('Tony Tanner', 8750)
INTO author (author_name, author_id) VALUES ('Tony Walton', 8751)
INTO author (author_name, author_id) VALUES ('Tony Westermayr', 8752)
INTO author (author_name, author_id) VALUES ('Toren Smith', 8753)
INTO author (author_name, author_id) VALUES ('Tori Amos', 8754)
INTO author (author_name, author_id) VALUES ('Toru Sasaki', 8755)
INTO author (author_name, author_id) VALUES ('Toshio Nakamura', 8756)
INTO author (author_name, author_id) VALUES ('Tracey Lawrence', 8757)
INTO author (author_name, author_id) VALUES ('Tracy Chevalier', 8758)
INTO author (author_name, author_id) VALUES ('Tracy Hickman', 8759)
INTO author (author_name, author_id) VALUES ('Tracy Kidder', 8760)
INTO author (author_name, author_id) VALUES ('Travel Foreman', 8761)
INTO author (author_name, author_id) VALUES ('Traverse Theatre', 8762)
INTO author (author_name, author_id) VALUES ('Travis Bogard', 8763)
INTO author (author_name, author_id) VALUES ('Travis Bradberry', 8764)
INTO author (author_name, author_id) VALUES ('Travis Charest', 8765)
INTO author (author_name, author_id) VALUES ('Travis Heerman', 8766)
INTO author (author_name, author_id) VALUES ('Trekkie Ritchie', 8767)
INTO author (author_name, author_id) VALUES ('Trevanian', 8768)
INTO author (author_name, author_id) VALUES ('Trevor Baxendale', 8769)
INTO author (author_name, author_id) VALUES ('Trevor Le Gassick', 8770)
INTO author (author_name, author_id) VALUES ('Trey Korte', 8771)
INTO author (author_name, author_id) VALUES ('Trey R. Baker', 8772)
INTO author (author_name, author_id) VALUES ('Tricia Hedge', 8773)
INTO author (author_name, author_id) VALUES ('Trina Robbins', 8774)
INTO author (author_name, author_id) VALUES ('Trina Schart Hyman', 8775)
INTO author (author_name, author_id) VALUES ('Trini Alvarado', 8776)
INTO author (author_name, author_id) VALUES ('Tristan Taormino', 8777)
INTO author (author_name, author_id) VALUES ('Troy Denning', 8778)
INTO author (author_name, author_id) VALUES ('Troy Howell', 8779)
INTO author (author_name, author_id) VALUES ('Truddi Chase', 8780)
INTO author (author_name, author_id) VALUES ('Trude Turnquist', 8781)
INTO author (author_name, author_id) VALUES ('Trudi Canavan', 8782)
INTO author (author_name, author_id) VALUES ('True Kelley', 8783)
INTO author (author_name, author_id) VALUES ('Truman Capote', 8784)
INTO author (author_name, author_id) VALUES ('Tsugumi Ohba', 8785)
INTO author (author_name, author_id) VALUES ('Tsutomu Nihei', 8786)
INTO author (author_name, author_id) VALUES ('Tucker Max', 8787)
INTO author (author_name, author_id) VALUES ('Tudor Humphries', 8788)
INTO author (author_name, author_id) VALUES ('Ty Templeton', 8789)
INTO author (author_name, author_id) VALUES ('Tyler Florence', 8790)
INTO author (author_name, author_id) VALUES ('Ul De Rico', 8791)
INTO author (author_name, author_id) VALUES ('Ulrike Wasel', 8792)
INTO author (author_name, author_id) VALUES ('Umberto Eco', 8793)
INTO author (author_name, author_id) VALUES ('Una Brankin', 8794)
INTO author (author_name, author_id) VALUES ('United Feature Syndication', 8795)
INTO author (author_name, author_id) VALUES ('Unknown', 8796)
INTO author (author_name, author_id) VALUES ('Upasika Kee Nanayon', 8797)
INTO author (author_name, author_id) VALUES ('Upton Sinclair', 8798)
INTO author (author_name, author_id) VALUES ('Ursula Bentley', 8799)
INTO author (author_name, author_id) VALUES ('Ursula Ferrigno', 8800)
INTO author (author_name, author_id) VALUES ('Virginia Alcott Sadock', 8881)
INTO author (author_name, author_id) VALUES ('Virginia Blain', 8882)
INTO author (author_name, author_id) VALUES ('Virginia C. Fowler', 8883)
INTO author (author_name, author_id) VALUES ('Virginia DeMarce', 8884)
INTO author (author_name, author_id) VALUES ('Virginia Hamilton Adair', 8885)
INTO author (author_name, author_id) VALUES ('Virginia Jewiss', 8886)
INTO author (author_name, author_id) VALUES ('Virginia Kantra', 8887)
INTO author (author_name, author_id) VALUES ('Virginia Lee Barnes', 8888)
INTO author (author_name, author_id) VALUES ('Virginia Lee Burton', 8889)
INTO author (author_name, author_id) VALUES ('Virginia Woolf', 8890)
INTO author (author_name, author_id) VALUES ('Vita Sackville-West', 8891)
INTO author (author_name, author_id) VALUES ('Vivian de Sola Pinto', 8892)
INTO author (author_name, author_id) VALUES ('Vivian Kogan', 8893)
INTO author (author_name, author_id) VALUES ('Vivien Jones', 8894)
INTO author (author_name, author_id) VALUES ('Vladimir Nabokov', 8895)
INTO author (author_name, author_id) VALUES ('Voltaire', 8896)
INTO author (author_name, author_id) VALUES ('Vox Day', 8897)
INTO author (author_name, author_id) VALUES ('Vsevolod Garshin', 8898)
INTO author (author_name, author_id) VALUES ('W. Chan Kim', 8899)
INTO author (author_name, author_id) VALUES ('W. Frederick Zimmerman', 8900) SELECT * FROM dual;

INSERT ALL
INTO author (author_name, author_id) VALUES ('W. Haden Blackman', 8901)
INTO author (author_name, author_id) VALUES ('W. Heath Robinson', 8902)
INTO author (author_name, author_id) VALUES ('W. Jason Gilmore', 8903)
INTO author (author_name, author_id) VALUES ('W. John Campbell', 8904)
INTO author (author_name, author_id) VALUES ('W. Michael Kelley', 8905)
INTO author (author_name, author_id) VALUES ('W. R. Johnson', 8906)
INTO author (author_name, author_id) VALUES ('W. Somerset Maugham', 8907)
INTO author (author_name, author_id) VALUES ('W. Terrence Gordon', 8908)
INTO author (author_name, author_id) VALUES ('W.A. McDevitte', 8909)
INTO author (author_name, author_id) VALUES ('W.E.B. Du Bois', 8910)
INTO author (author_name, author_id) VALUES ('W.E.B. Griffin', 8911)
INTO author (author_name, author_id) VALUES ('W.F. Deedes', 8912)
INTO author (author_name, author_id) VALUES ('W.G. Sebald', 8913)
INTO author (author_name, author_id) VALUES ('W.H. Auden', 8914)
INTO author (author_name, author_id) VALUES ('W.H.D. Rouse', 8915)
INTO author (author_name, author_id) VALUES ('W.J. McCormack', 8916)
INTO author (author_name, author_id) VALUES ('W.M. Geldart', 8917)
INTO author (author_name, author_id) VALUES ('W.S. Hett', 8918)
INTO author (author_name, author_id) VALUES ('W.S. Merwin', 8919)
INTO author (author_name, author_id) VALUES ('Wade Davis', 8920)
INTO author (author_name, author_id) VALUES ('Wade Von Grawbadger', 8921)
INTO author (author_name, author_id) VALUES ('Walden Wong', 8922)
INTO author (author_name, author_id) VALUES ('Walker Percy', 8923)
INTO author (author_name, author_id) VALUES ('Wallace Fowlie', 8924)
INTO author (author_name, author_id) VALUES ('Wallace Stegner', 8925)
INTO author (author_name, author_id) VALUES ('Wallace Tripp', 8926)
INTO author (author_name, author_id) VALUES ('Wally Lamb', 8927)
INTO author (author_name, author_id) VALUES ('Walt Boyes', 8928)
INTO author (author_name, author_id) VALUES ('Walt Disney Company', 8929)
INTO author (author_name, author_id) VALUES ('Walt Whitman', 8930)
INTO author (author_name, author_id) VALUES ('Walter Benjamin', 8931)
INTO author (author_name, author_id) VALUES ('Walter Blair', 8932)
INTO author (author_name, author_id) VALUES ('Walter Blanco', 8933)
INTO author (author_name, author_id) VALUES ('Walter Crane', 8934)
INTO author (author_name, author_id) VALUES ('Walter Cronkite', 8935)
INTO author (author_name, author_id) VALUES ('Walter de la Mare', 8936)
INTO author (author_name, author_id) VALUES ('Walter Dean Myers', 8937)
INTO author (author_name, author_id) VALUES ('Walter Farley', 8938)
INTO author (author_name, author_id) VALUES ('Walter Foster Creative Team', 8939)
INTO author (author_name, author_id) VALUES ('Walter Hamilton', 8940)
INTO author (author_name, author_id) VALUES ('Walter Hampden', 8941)
INTO author (author_name, author_id) VALUES ('Walter Hartmann', 8942)
INTO author (author_name, author_id) VALUES ('Walter Hettche', 8943)
INTO author (author_name, author_id) VALUES ('Walter Hooper', 8944)
INTO author (author_name, author_id) VALUES ('Walter Isaacson', 8945)
INTO author (author_name, author_id) VALUES ('Walter J. Cobb', 8946)
INTO author (author_name, author_id) VALUES ('Walter J. Savitch', 8947)
INTO author (author_name, author_id) VALUES ('Walter Jon Williams', 8948)
INTO author (author_name, author_id) VALUES ('Walter Karig', 8949)
INTO author (author_name, author_id) VALUES ('Walter Kaufmann', 8950)
INTO author (author_name, author_id) VALUES ('Walter Kirn', 8951)
INTO author (author_name, author_id) VALUES ('Walter Lowrie', 8952)
INTO author (author_name, author_id) VALUES ('Walter Miller', 8953)
INTO author (author_name, author_id) VALUES ('Walter Pater', 8954)
INTO author (author_name, author_id) VALUES ('Walter Ritoku Robinson', 8955)
INTO author (author_name, author_id) VALUES ('Walter Rodney', 8956)
INTO author (author_name, author_id) VALUES ('Walter Scott', 8957)
INTO author (author_name, author_id) VALUES ('Walter Simonson', 8958)
INTO author (author_name, author_id) VALUES ('Walter Starkie', 8959)
INTO author (author_name, author_id) VALUES ('Walter Trier', 8960)
INTO author (author_name, author_id) VALUES ('Walter W. Arndt', 8961)
INTO author (author_name, author_id) VALUES ('Wanda Sykes', 8962)
INTO author (author_name, author_id) VALUES ('Wang Wei', 8963)
INTO author (author_name, author_id) VALUES ('Waris Dirie', 8964)
INTO author (author_name, author_id) VALUES ('Warner Berthoff', 8965)
INTO author (author_name, author_id) VALUES ('Warner Books', 8966)
INTO author (author_name, author_id) VALUES ('Warren B. Smith', 8967)
INTO author (author_name, author_id) VALUES ('Warren Bennis', 8968)
INTO author (author_name, author_id) VALUES ('Warren Chang', 8969)
INTO author (author_name, author_id) VALUES ('Warren Ellis', 8970)
INTO author (author_name, author_id) VALUES ('Warren G. Bennis', 8971)
INTO author (author_name, author_id) VALUES ('Warren Murphy', 8972)
INTO author (author_name, author_id) VALUES ('Warren Pleece', 8973)
INTO author (author_name, author_id) VALUES ('Warren Roberts', 8974)
INTO author (author_name, author_id) VALUES ('Warren W. Wiersbe', 8975)
INTO author (author_name, author_id) VALUES ('Warshaw Hope', 8976)
INTO author (author_name, author_id) VALUES ('Wesley Dennis', 9002)
INTO author (author_name, author_id) VALUES ('Wesley Martin', 9003)
INTO author (author_name, author_id) VALUES ('Western Sonoma County Historical Society', 9004)
INTO author (author_name, author_id) VALUES ('Wilbur Smith', 9005)
INTO author (author_name, author_id) VALUES ('Wilfred Owen', 9006)
INTO author (author_name, author_id) VALUES ('Wilhelm Grimm', 9007)
INTO author (author_name, author_id) VALUES ('Wilkie Collins', 9008)
INTO author (author_name, author_id) VALUES ('Will Durant', 9009)
INTO author (author_name, author_id) VALUES ('Will Eisner', 9010)
INTO author (author_name, author_id) VALUES ('Will Ferguson', 9011)
INTO author (author_name, author_id) VALUES ('Will Focht', 9012)
INTO author (author_name, author_id) VALUES ('Will Kymlicka', 9013)
INTO author (author_name, author_id) VALUES ('Will Patten', 9014)
INTO author (author_name, author_id) VALUES ('Will Wright', 9015)
INTO author (author_name, author_id) VALUES ('Willa Cather', 9016)
INTO author (author_name, author_id) VALUES ('Willa Muir', 9017)
INTO author (author_name, author_id) VALUES ('Willa Okati', 9018)
INTO author (author_name, author_id) VALUES ('Willard R. Trask', 9019)
INTO author (author_name, author_id) VALUES ('Willard Van Orman Quine', 9020)
INTO author (author_name, author_id) VALUES ('William Jones', 9021)
INTO author (author_name, author_id) VALUES ('William Anderson', 9022)
INTO author (author_name, author_id) VALUES ('William James', 9023)
INTO author (author_name, author_id) VALUES ('William A. Cohen', 9024)
INTO author (author_name, author_id) VALUES ('William A. Oldfather', 9025)
INTO author (author_name, author_id) VALUES ('William Allan', 9026)
INTO author (author_name, author_id) VALUES ('William Andrewes', 9027)
INTO author (author_name, author_id) VALUES ('William Arrow', 9028)
INTO author (author_name, author_id) VALUES ('William Arrowsmith', 9029)
INTO author (author_name, author_id) VALUES ('William Barrett', 9030)
INTO author (author_name, author_id) VALUES ('William Bedell Stanford', 9031)
INTO author (author_name, author_id) VALUES ('William Beebe', 9032)
INTO author (author_name, author_id) VALUES ('William Blake', 9033)
INTO author (author_name, author_id) VALUES ('William Boyd', 9034)
INTO author (author_name, author_id) VALUES ('William C. Carter', 9035)
INTO author (author_name, author_id) VALUES ('William C. Davis', 9036)
INTO author (author_name, author_id) VALUES ('William C. Dowling', 9037)
INTO author (author_name, author_id) VALUES ('William Camann', 9038)
INTO author (author_name, author_id) VALUES ('Zoë Ross', 9195)
INTO author (author_name, author_id) VALUES ('Zolar', 9196)
INTO author (author_name, author_id) VALUES ('Zoltan Ab di-Nagy', 9197)
INTO author (author_name, author_id) VALUES ('Zora Neale Hurston', 9198)
INTO author (author_name, author_id) VALUES ('Zoran Jevtić', 9199)
INTO author (author_name, author_id) VALUES ('Αχιλλέας Κυριακίδης', 9200)
INTO author (author_name, author_id) VALUES ('Λία Βουτσοπούλου', 9201)
INTO author (author_name, author_id) VALUES ('Νίκος Παναγιωτόπουλος', 9202)
INTO author (author_name, author_id) VALUES ('Валериан Альбанов', 9203)
INTO author (author_name, author_id) VALUES ('Михаил Булгаков', 9204)
INTO author (author_name, author_id) VALUES ('إدوارد سعيد', 9205)
INTO author (author_name, author_id) VALUES ('جبران خليل جبران', 9206)
INTO author (author_name, author_id) VALUES ('دل آرا قهرمان', 9207)
INTO author (author_name, author_id) VALUES ('صنع الله إبراهيم', 9208)
INTO author (author_name, author_id) VALUES ('عین له غریب', 9209)
INTO author (author_name, author_id) VALUES ('فروغ پوریاوری', 9210)
INTO author (author_name, author_id) VALUES ('محمدعلی مهمان‌نوازان', 9211)
INTO author (author_name, author_id) VALUES ('محمود منقذ الهاشمي', 9212)
INTO author (author_name, author_id) VALUES ('مریم کاظمی‌تبار', 9213)
INTO author (author_name, author_id) VALUES ('あずま きよひこ', 9214)
INTO author (author_name, author_id) VALUES ('伊藤潤二', 9215)
INTO author (author_name, author_id) VALUES ('大場 つぐみ', 9216)
INTO author (author_name, author_id) VALUES ('大暮 維人', 9217)
INTO author (author_name, author_id) VALUES ('季思聰', 9218)
INTO author (author_name, author_id) VALUES ('小川 彌生', 9219)
INTO author (author_name, author_id) VALUES ('小畑 健', 9220)
INTO author (author_name, author_id) VALUES ('小野 不由美', 9221)
INTO author (author_name, author_id) VALUES ('山田 章博', 9222)
INTO author (author_name, author_id) VALUES ('張定綺', 9223)
INTO author (author_name, author_id) VALUES ('彭倩文', 9224)
INTO author (author_name, author_id) VALUES ('志水 ゆき', 9225)
INTO author (author_name, author_id) VALUES ('托爾金', 9226)
INTO author (author_name, author_id) VALUES ('方郁仁', 9227)
INTO author (author_name, author_id) VALUES ('朱學恆', 9228)
INTO author (author_name, author_id) VALUES ('林靜華', 9229)
INTO author (author_name, author_id) VALUES ('森 薫', 9230)
INTO author (author_name, author_id) VALUES ('橋口 たかし', 9231)
INTO author (author_name, author_id) VALUES ('皇冠編譯組', 9232)
INTO author (author_name, author_id) VALUES ('神尾葉子', 9233)
INTO author (author_name, author_id) VALUES ('荒川弘', 9234)
INTO author (author_name, author_id) VALUES ('趙丕慧', 9235) SELECT * FROM dual;

COMMIT;
