INSERT ALL
INTO publisher (publisher_name, publisher_id) VALUES ('10/18', 1)
INTO publisher (publisher_name, publisher_id) VALUES ('1st Book Library', 2)
INTO publisher (publisher_name, publisher_id) VALUES ('1st World Library', 3)
INTO publisher (publisher_name, publisher_id) VALUES ('A and C Black (Childrens books)', 4)
INTO publisher (publisher_name, publisher_id) VALUES ('A Harvest Book/Harcourt Inc.', 5)
INTO publisher (publisher_name, publisher_id) VALUES ('A K PETERS', 6)
INTO publisher (publisher_name, publisher_id) VALUES ('AA World Services', 7)
INTO publisher (publisher_name, publisher_id) VALUES ('Abacus', 8)
INTO publisher (publisher_name, publisher_id) VALUES ('Abacus Books', 9)
INTO publisher (publisher_name, publisher_id) VALUES ('Abacus Books (London)', 10)
INTO publisher (publisher_name, publisher_id) VALUES ('Abdo Publishing Company', 11)
INTO publisher (publisher_name, publisher_id) VALUES ('Abingdon Press', 12)
INTO publisher (publisher_name, publisher_id) VALUES ('Abradale Books/Harry N. Abrams', 13)
INTO publisher (publisher_name, publisher_id) VALUES ('Abraham Guillen Press', 14)
INTO publisher (publisher_name, publisher_id) VALUES ('Abrams', 15)
INTO publisher (publisher_name, publisher_id) VALUES ('Absolute Press', 16)
INTO publisher (publisher_name, publisher_id) VALUES ('Abstract Studio', 17)
INTO publisher (publisher_name, publisher_id) VALUES ('Academic Press', 18)
INTO publisher (publisher_name, publisher_id) VALUES ('Academica Press', 19)
INTO publisher (publisher_name, publisher_id) VALUES ('Academy Chicago Publishers', 20)
INTO publisher (publisher_name, publisher_id) VALUES ('Ace', 21)
INTO publisher (publisher_name, publisher_id) VALUES ('Ace Book', 22)
INTO publisher (publisher_name, publisher_id) VALUES ('Ace Books', 23)
INTO publisher (publisher_name, publisher_id) VALUES ('Ace Hardcover', 24)
INTO publisher (publisher_name, publisher_id) VALUES ('Ace Trade', 25)
INTO publisher (publisher_name, publisher_id) VALUES ('Ace/SFBC', 26)
INTO publisher (publisher_name, publisher_id) VALUES ('Acento Editorial', 27)
INTO publisher (publisher_name, publisher_id) VALUES ('Acropolis Books (NY)', 28)
INTO publisher (publisher_name, publisher_id) VALUES ('Actes Sud', 29)
INTO publisher (publisher_name, publisher_id) VALUES ('Adamant Media Corporation', 30)
INTO publisher (publisher_name, publisher_id) VALUES ('Adams Media', 31)
INTO publisher (publisher_name, publisher_id) VALUES ('Addison Wesley', 32)
INTO publisher (publisher_name, publisher_id) VALUES ('Addison Wesley Publishing Company', 33)
INTO publisher (publisher_name, publisher_id) VALUES ('Addison-Wesley Professional', 34)
INTO publisher (publisher_name, publisher_id) VALUES ('ADV Manga', 35)
INTO publisher (publisher_name, publisher_id) VALUES ('Advantage World Press', 36)
INTO publisher (publisher_name, publisher_id) VALUES ('Adventures Unlimited Press', 37)
INTO publisher (publisher_name, publisher_id) VALUES ('Aegypan', 38)
INTO publisher (publisher_name, publisher_id) VALUES ('Aerie', 39)
INTO publisher (publisher_name, publisher_id) VALUES ('AHA! Process', 40)
INTO publisher (publisher_name, publisher_id) VALUES ('AIT Planet Lar', 41)
INTO publisher (publisher_name, publisher_id) VALUES ('Aivia Press', 42)
INTO publisher (publisher_name, publisher_id) VALUES ('AK Press', 43)
INTO publisher (publisher_name, publisher_id) VALUES ('Akashic Books/Punk Planet Books', 44)
INTO publisher (publisher_name, publisher_id) VALUES ('Aladdin', 45)
INTO publisher (publisher_name, publisher_id) VALUES ('Aladdin Paperbacks', 46)
INTO publisher (publisher_name, publisher_id) VALUES ('Alan Rodgers Books', 47)
INTO publisher (publisher_name, publisher_id) VALUES ('Albert Whitman Company', 48)
INTO publisher (publisher_name, publisher_id) VALUES ('Albin Michel', 49)
INTO publisher (publisher_name, publisher_id) VALUES ('Albury Publishing', 50)
INTO publisher (publisher_name, publisher_id) VALUES ('Alcoholics Anonymous World Services Inc', 51)
INTO publisher (publisher_name, publisher_id) VALUES ('Alderac Entertainment Group', 52)
INTO publisher (publisher_name, publisher_id) VALUES ('Alderac Entertainment Group (AEG)', 53)
INTO publisher (publisher_name, publisher_id) VALUES ('Alfabeta Bokförlag', 54)
INTO publisher (publisher_name, publisher_id) VALUES ('Alfaguara', 55)
INTO publisher (publisher_name, publisher_id) VALUES ('Alfaguara Infantil', 56)
INTO publisher (publisher_name, publisher_id) VALUES ('Alfred A. Knopf', 57)
INTO publisher (publisher_name, publisher_id) VALUES ('Alfred A. Knopf Inc.', 58)
INTO publisher (publisher_name, publisher_id) VALUES ('Alfred A. Knopf Books for Young Readers', 59)
INTO publisher (publisher_name, publisher_id) VALUES ('Alfred A. Knopf Borzoi Books', 60)
INTO publisher (publisher_name, publisher_id) VALUES ('Alfred A.Knopf', 61)
INTO publisher (publisher_name, publisher_id) VALUES ('Algonquin Books', 62)
INTO publisher (publisher_name, publisher_id) VALUES ('Alianza Editorial', 63)
INTO publisher (publisher_name, publisher_id) VALUES ('Alison Green Books', 64)
INTO publisher (publisher_name, publisher_id) VALUES ('Allen and Ulwin', 65)
INTO publisher (publisher_name, publisher_id) VALUES ('Allen Lane', 66)
INTO publisher (publisher_name, publisher_id) VALUES ('Alliance Publishing', 67)
INTO publisher (publisher_name, publisher_id) VALUES ('Allworth', 68)
INTO publisher (publisher_name, publisher_id) VALUES ('Allyn and Bacon', 69)
INTO publisher (publisher_name, publisher_id) VALUES ('Alpha', 70)
INTO publisher (publisher_name, publisher_id) VALUES ('Alpha Books', 71)
INTO publisher (publisher_name, publisher_id) VALUES ('Alyson Books', 72)
INTO publisher (publisher_name, publisher_id) VALUES ('Amadeus', 73)
INTO publisher (publisher_name, publisher_id) VALUES ('Amereon Limited', 74)
INTO publisher (publisher_name, publisher_id) VALUES ('Amereon Ltd', 75)
INTO publisher (publisher_name, publisher_id) VALUES ('America''s Test Kitchen', 76)
INTO publisher (publisher_name, publisher_id) VALUES ('American Diabetes Association', 77)
INTO publisher (publisher_name, publisher_id) VALUES ('American Girl Publishing Inc', 78)
INTO publisher (publisher_name, publisher_id) VALUES ('American University in Cairo Press', 79)
INTO publisher (publisher_name, publisher_id) VALUES ('Amherst Media', 80)
INTO publisher (publisher_name, publisher_id) VALUES ('Amherst Media Inc.', 81)
INTO publisher (publisher_name, publisher_id) VALUES ('Amistad', 82)
INTO publisher (publisher_name, publisher_id) VALUES ('Amistad Press', 83)
INTO publisher (publisher_name, publisher_id) VALUES ('AMR/Advanced Management Reports', 84)
INTO publisher (publisher_name, publisher_id) VALUES ('Anagrama', 85)
INTO publisher (publisher_name, publisher_id) VALUES ('Anchor', 86)
INTO publisher (publisher_name, publisher_id) VALUES ('Anchor Bible', 87)
INTO publisher (publisher_name, publisher_id) VALUES ('Anchor Books', 88)
INTO publisher (publisher_name, publisher_id) VALUES ('Anchor Books/Knopf Doubleday Publishing Group', 89)
INTO publisher (publisher_name, publisher_id) VALUES ('Anchor Canada', 90)
INTO publisher (publisher_name, publisher_id) VALUES ('Andrews and McMeel', 91)
INTO publisher (publisher_name, publisher_id) VALUES ('Andrews McMeel Publishing', 92)
INTO publisher (publisher_name, publisher_id) VALUES ('Ann Arbor Media', 93)
INTO publisher (publisher_name, publisher_id) VALUES ('Annick Press', 94)
INTO publisher (publisher_name, publisher_id) VALUES ('Applause Books', 95)
INTO publisher (publisher_name, publisher_id) VALUES ('Applause Theatre and Cinema Book Publishers', 96)
INTO publisher (publisher_name, publisher_id) VALUES ('Apple', 97)
INTO publisher (publisher_name, publisher_id) VALUES ('Apple Paperbacks (Scholastic)', 98)
INTO publisher (publisher_name, publisher_id) VALUES ('Applewood Books', 99)
INTO publisher (publisher_name, publisher_id) VALUES ('Apress', 100)
INTO publisher (publisher_name, publisher_id) VALUES ('Arbordale Publishing', 101)
INTO publisher (publisher_name, publisher_id) VALUES ('Arcade Publishing', 102)
INTO publisher (publisher_name, publisher_id) VALUES ('Arcadia Publishing', 103)
INTO publisher (publisher_name, publisher_id) VALUES ('Arcadia Publishing (SC)', 104)
INTO publisher (publisher_name, publisher_id) VALUES ('Archaia', 105)
INTO publisher (publisher_name, publisher_id) VALUES ('Archie Comics', 106)
INTO publisher (publisher_name, publisher_id) VALUES ('Archipelago Books', 107)
INTO publisher (publisher_name, publisher_id) VALUES ('Arden Shakespeare', 108)
INTO publisher (publisher_name, publisher_id) VALUES ('Aris and Phillips', 109)
INTO publisher (publisher_name, publisher_id) VALUES ('Aris and Phillips', 110)
INTO publisher (publisher_name, publisher_id) VALUES ('Arkana', 111)
INTO publisher (publisher_name, publisher_id) VALUES ('Arkana/Penguin', 112)
INTO publisher (publisher_name, publisher_id) VALUES ('Arkham House Publishers', 113)
INTO publisher (publisher_name, publisher_id) VALUES ('Arléa', 114)
INTO publisher (publisher_name, publisher_id) VALUES ('Arlington House', 115)
INTO publisher (publisher_name, publisher_id) VALUES ('Arrow', 116)
INTO publisher (publisher_name, publisher_id) VALUES ('Arrow (A Division of Random House Group)', 117)
INTO publisher (publisher_name, publisher_id) VALUES ('Arrow Books', 118)
INTO publisher (publisher_name, publisher_id) VALUES ('Arrow Books Ltd', 119)
INTO publisher (publisher_name, publisher_id) VALUES ('Arsenal Pulp Press', 120)
INTO publisher (publisher_name, publisher_id) VALUES ('Arthur A. Levine', 121)
INTO publisher (publisher_name, publisher_id) VALUES ('Arthur A. Levine Books', 122)
INTO publisher (publisher_name, publisher_id) VALUES ('Arthur A. Levine Books / Scholastic Inc.', 123)
INTO publisher (publisher_name, publisher_id) VALUES ('Artisan', 124)
INTO publisher (publisher_name, publisher_id) VALUES ('Arts Publications', 125)
INTO publisher (publisher_name, publisher_id) VALUES ('ASCD', 126)
INTO publisher (publisher_name, publisher_id) VALUES ('Ash Tree Publishing', 127)
INTO publisher (publisher_name, publisher_id) VALUES ('Ash-Tree Press', 128)
INTO publisher (publisher_name, publisher_id) VALUES ('Aspect', 129)
INTO publisher (publisher_name, publisher_id) VALUES ('Association for Scottish Literary Studies', 130)
INTO publisher (publisher_name, publisher_id) VALUES ('Association for Supervision and Curriculum Development', 131)
INTO publisher (publisher_name, publisher_id) VALUES ('Atelos Press', 132)
INTO publisher (publisher_name, publisher_id) VALUES ('Atheneum', 133)
INTO publisher (publisher_name, publisher_id) VALUES ('Atheneum Books', 134)
INTO publisher (publisher_name, publisher_id) VALUES ('Atheneum Books for Young Readers', 135)
INTO publisher (publisher_name, publisher_id) VALUES ('Atheneum Books for Young Readers: Richard Jackson Books', 136)
INTO publisher (publisher_name, publisher_id) VALUES ('Atheneum/Richard Jackson Books', 137)
INTO publisher (publisher_name, publisher_id) VALUES ('Atlantic', 138)
INTO publisher (publisher_name, publisher_id) VALUES ('Atlantic Books', 139)
INTO publisher (publisher_name, publisher_id) VALUES ('Atlantic Books (UK)', 140)
INTO publisher (publisher_name, publisher_id) VALUES ('Atlantic Monthly Press', 141)
INTO publisher (publisher_name, publisher_id) VALUES ('Atlantic Monthly Press (NYC)', 142)
INTO publisher (publisher_name, publisher_id) VALUES ('Atlas Books/HarperCollins Publishers', 143)
INTO publisher (publisher_name, publisher_id) VALUES ('Atria Books', 144)
INTO publisher (publisher_name, publisher_id) VALUES ('Audio Literature', 145)
INTO publisher (publisher_name, publisher_id) VALUES ('Audio Partners', 146)
INTO publisher (publisher_name, publisher_id) VALUES ('Audio Renaissance', 147)
INTO publisher (publisher_name, publisher_id) VALUES ('AudioGO', 148)
INTO publisher (publisher_name, publisher_id) VALUES ('AudioText', 149)
INTO publisher (publisher_name, publisher_id) VALUES ('Augsburg Fortress Publishing', 150)
INTO publisher (publisher_name, publisher_id) VALUES ('Aurum', 151)
INTO publisher (publisher_name, publisher_id) VALUES ('Aurum Press', 152)
INTO publisher (publisher_name, publisher_id) VALUES ('Authorhouse', 153)
INTO publisher (publisher_name, publisher_id) VALUES ('AVA Publishing', 154)
INTO publisher (publisher_name, publisher_id) VALUES ('Avalon Travel', 155)
INTO publisher (publisher_name, publisher_id) VALUES ('Ave Maria Press', 156)
INTO publisher (publisher_name, publisher_id) VALUES ('Avenel Books', 157)
INTO publisher (publisher_name, publisher_id) VALUES ('Avery', 158)
INTO publisher (publisher_name, publisher_id) VALUES ('Avery Publishing Group', 159)
INTO publisher (publisher_name, publisher_id) VALUES ('Avon', 160)
INTO publisher (publisher_name, publisher_id) VALUES ('Avon Books', 161)
INTO publisher (publisher_name, publisher_id) VALUES ('Avon Books (AvoNova)', 162)
INTO publisher (publisher_name, publisher_id) VALUES ('Avon Books (P)', 163)
INTO publisher (publisher_name, publisher_id) VALUES ('Avon HarperCollins', 164)
INTO publisher (publisher_name, publisher_id) VALUES ('AvonEos', 165)
INTO publisher (publisher_name, publisher_id) VALUES ('Award Books', 166)
INTO publisher (publisher_name, publisher_id) VALUES ('B Books', 167)
INTO publisher (publisher_name, publisher_id) VALUES ('B Fiction', 168)
INTO publisher (publisher_name, publisher_id) VALUES ('B.E.S. Publishing', 169)
INTO publisher (publisher_name, publisher_id) VALUES ('BandH Publishing Group', 170)
INTO publisher (publisher_name, publisher_id) VALUES ('Babel', 171)
INTO publisher (publisher_name, publisher_id) VALUES ('Back Bay', 172)
INTO publisher (publisher_name, publisher_id) VALUES ('Back Bay Books', 173)
INTO publisher (publisher_name, publisher_id) VALUES ('Backinprint.com', 174)
INTO publisher (publisher_name, publisher_id) VALUES ('Backstage Books', 175)
INTO publisher (publisher_name, publisher_id) VALUES ('Celestial Arts', 366)
INTO publisher (publisher_name, publisher_id) VALUES ('Cemetery Dance Publications', 367)
INTO publisher (publisher_name, publisher_id) VALUES ('Cengage Learning', 368)
INTO publisher (publisher_name, publisher_id) VALUES ('Center Point', 369)
INTO publisher (publisher_name, publisher_id) VALUES ('Century', 370)
INTO publisher (publisher_name, publisher_id) VALUES ('Chalice Press', 371)
INTO publisher (publisher_name, publisher_id) VALUES ('Challenge Press Inc./Challcrest Press', 372)
INTO publisher (publisher_name, publisher_id) VALUES ('Changeling Press', 373)
INTO publisher (publisher_name, publisher_id) VALUES ('Chaosium', 374)
INTO publisher (publisher_name, publisher_id) VALUES ('Charles Scribner''s Sons', 375)
INTO publisher (publisher_name, publisher_id) VALUES ('Charlesbridge', 376)
INTO publisher (publisher_name, publisher_id) VALUES ('Charnwood', 377)
INTO publisher (publisher_name, publisher_id) VALUES ('Chartwell Books', 378)
INTO publisher (publisher_name, publisher_id) VALUES ('Chatto Windus', 379)
INTO publisher (publisher_name, publisher_id) VALUES ('Chatto and Windus', 380)
INTO publisher (publisher_name, publisher_id) VALUES ('Chatto and Windus', 381)
INTO publisher (publisher_name, publisher_id) VALUES ('Checkmark Books', 382)
INTO publisher (publisher_name, publisher_id) VALUES ('Chelsea House Publications', 383)
INTO publisher (publisher_name, publisher_id) VALUES ('Chelsea House Publishers', 384)
INTO publisher (publisher_name, publisher_id) VALUES ('Cherry Lane Music Company', 385)
INTO publisher (publisher_name, publisher_id) VALUES ('Cherry Red Books', 386)
INTO publisher (publisher_name, publisher_id) VALUES ('Chicago Review Press', 387)
INTO publisher (publisher_name, publisher_id) VALUES ('Chicken House', 388)
INTO publisher (publisher_name, publisher_id) VALUES ('Chicken House / Scholastic', 389)
INTO publisher (publisher_name, publisher_id) VALUES ('Child''s Play International', 390)
INTO publisher (publisher_name, publisher_id) VALUES ('Children''s Classics', 391)
INTO publisher (publisher_name, publisher_id) VALUES ('Children''s Press(CT)', 392)
INTO publisher (publisher_name, publisher_id) VALUES ('Chosen Books', 393)
INTO publisher (publisher_name, publisher_id) VALUES ('Christian Classics', 394)
INTO publisher (publisher_name, publisher_id) VALUES ('Chronicle Books', 395)
INTO publisher (publisher_name, publisher_id) VALUES ('Chu Hartley Publishers LLC', 396)
INTO publisher (publisher_name, publisher_id) VALUES ('Churchill Livingstone', 397)
INTO publisher (publisher_name, publisher_id) VALUES ('Circlet Press', 398)
INTO publisher (publisher_name, publisher_id) VALUES ('Círculo de Lectores', 399)
INTO publisher (publisher_name, publisher_id) VALUES ('Cisne', 400)
INTO publisher (publisher_name, publisher_id) VALUES ('Cistercian Publications', 401)
INTO publisher (publisher_name, publisher_id) VALUES ('Citadel', 402)
INTO publisher (publisher_name, publisher_id) VALUES ('Citadel Press', 403)
INTO publisher (publisher_name, publisher_id) VALUES ('City Lights', 404)
INTO publisher (publisher_name, publisher_id) VALUES ('City Lights Publishers', 405)
INTO publisher (publisher_name, publisher_id) VALUES ('Civitas Books', 406)
INTO publisher (publisher_name, publisher_id) VALUES ('Claassen Verlag', 407)
INTO publisher (publisher_name, publisher_id) VALUES ('Clarendon Press', 408)
INTO publisher (publisher_name, publisher_id) VALUES ('Clarion Books', 409)
INTO publisher (publisher_name, publisher_id) VALUES ('Clarity Press', 410)
INTO publisher (publisher_name, publisher_id) VALUES ('Clarkson Potter', 411)
INTO publisher (publisher_name, publisher_id) VALUES ('Clarkson Potter Publishers', 412)
INTO publisher (publisher_name, publisher_id) VALUES ('Clarkson Potter/Publishers', 413)
INTO publisher (publisher_name, publisher_id) VALUES ('Classic Books', 414)
INTO publisher (publisher_name, publisher_id) VALUES ('Cleis Press', 415)
INTO publisher (publisher_name, publisher_id) VALUES ('Cliffs Notes', 416)
INTO publisher (publisher_name, publisher_id) VALUES ('CMX', 417)
INTO publisher (publisher_name, publisher_id) VALUES ('Coffee House Press', 418)
INTO publisher (publisher_name, publisher_id) VALUES ('Cold Spring Harbor Laboratory Press', 419)
INTO publisher (publisher_name, publisher_id) VALUES ('Cold Spring Press', 420)
INTO publisher (publisher_name, publisher_id) VALUES ('Collection of Historical Scientific Instruments', 421)
INTO publisher (publisher_name, publisher_id) VALUES ('Collector''s Library', 422)
INTO publisher (publisher_name, publisher_id) VALUES ('Collectors Library', 423)
INTO publisher (publisher_name, publisher_id) VALUES ('Collier Books', 424)
INTO publisher (publisher_name, publisher_id) VALUES ('Collins', 425)
INTO publisher (publisher_name, publisher_id) VALUES ('Collins Design', 426)
INTO publisher (publisher_name, publisher_id) VALUES ('Collins Modern Classics', 427)
INTO publisher (publisher_name, publisher_id) VALUES ('Collins Publishers', 428)
INTO publisher (publisher_name, publisher_id) VALUES ('Collins Reference', 429)
INTO publisher (publisher_name, publisher_id) VALUES ('Columbia Pictures Pubns', 430)
INTO publisher (publisher_name, publisher_id) VALUES ('Columbia University Press', 431)
INTO publisher (publisher_name, publisher_id) VALUES ('ComicsLit', 432)
INTO publisher (publisher_name, publisher_id) VALUES ('ComicsOne Corporation', 433)
INTO publisher (publisher_name, publisher_id) VALUES ('Companhia das Letras', 434)
INTO publisher (publisher_name, publisher_id) VALUES ('Conari Press', 435)
INTO publisher (publisher_name, publisher_id) VALUES ('Condor Books', 436)
INTO publisher (publisher_name, publisher_id) VALUES ('Contemporary Books', 437)
INTO publisher (publisher_name, publisher_id) VALUES ('Contemporary French Fiction', 438)
INTO publisher (publisher_name, publisher_id) VALUES ('Continuum', 439)
INTO publisher (publisher_name, publisher_id) VALUES ('Editions de l''Olivier', 620)
INTO publisher (publisher_name, publisher_id) VALUES ('Éditions de L''Olivier', 621)
INTO publisher (publisher_name, publisher_id) VALUES ('Éditions de Minuit', 622)
INTO publisher (publisher_name, publisher_id) VALUES ('Editions du Rocher', 623)
INTO publisher (publisher_name, publisher_id) VALUES ('Éditions du Rocher', 624)
INTO publisher (publisher_name, publisher_id) VALUES ('Editions Gallimard', 625)
INTO publisher (publisher_name, publisher_id) VALUES ('Editorial Diana', 626)
INTO publisher (publisher_name, publisher_id) VALUES ('Editorial Juventud', 627)
INTO publisher (publisher_name, publisher_id) VALUES ('Editorial Presença', 628)
INTO publisher (publisher_name, publisher_id) VALUES ('Editorial RM', 629)
INTO publisher (publisher_name, publisher_id) VALUES ('Edwin Mellen Press', 630)
INTO publisher (publisher_name, publisher_id) VALUES ('Eerdmans', 631)
INTO publisher (publisher_name, publisher_id) VALUES ('Egmont Books Ltd', 632)
INTO publisher (publisher_name, publisher_id) VALUES ('Egmont Children''s Books', 633)
INTO publisher (publisher_name, publisher_id) VALUES ('El Paso Norte Press', 634)
INTO publisher (publisher_name, publisher_id) VALUES ('Element', 635)
INTO publisher (publisher_name, publisher_id) VALUES ('Ellora''s Cave', 636)
INTO publisher (publisher_name, publisher_id) VALUES ('Elloras Cave', 637)
INTO publisher (publisher_name, publisher_id) VALUES ('Ember', 638)
INTO publisher (publisher_name, publisher_id) VALUES ('EMC/Paradigm Publishing', 639)
INTO publisher (publisher_name, publisher_id) VALUES ('Emece Editores', 640)
INTO publisher (publisher_name, publisher_id) VALUES ('Emecé Editores', 641)
INTO publisher (publisher_name, publisher_id) VALUES ('Eminent Lives', 642)
INTO publisher (publisher_name, publisher_id) VALUES ('Encounter Books', 643)
INTO publisher (publisher_name, publisher_id) VALUES ('Enitharmon Press', 644)
INTO publisher (publisher_name, publisher_id) VALUES ('Eos', 645)
INTO publisher (publisher_name, publisher_id) VALUES ('Eraserhead Press', 646)
INTO publisher (publisher_name, publisher_id) VALUES ('Eros Comix', 647)
INTO publisher (publisher_name, publisher_id) VALUES ('Europa Editions', 648)
INTO publisher (publisher_name, publisher_id) VALUES ('Evans Brothers', 649)
INTO publisher (publisher_name, publisher_id) VALUES ('Everyman', 650)
INTO publisher (publisher_name, publisher_id) VALUES ('Everyman Chess', 651)
INTO publisher (publisher_name, publisher_id) VALUES ('Everyman Library / Overlook Press', 652)
INTO publisher (publisher_name, publisher_id) VALUES ('Everyman Paperback Classics', 653)
INTO publisher (publisher_name, publisher_id) VALUES ('Everyman Paperbacks', 654)
INTO publisher (publisher_name, publisher_id) VALUES ('Everyman''s Library', 655)
INTO publisher (publisher_name, publisher_id) VALUES ('Everyman''s Library 234', 656)
INTO publisher (publisher_name, publisher_id) VALUES ('Everyman''s Library Classics', 657)
INTO publisher (publisher_name, publisher_id) VALUES ('Everymans Library', 658)
INTO publisher (publisher_name, publisher_id) VALUES ('Exact Change', 659)
INTO publisher (publisher_name, publisher_id) VALUES ('Express Publishing', 660)
INTO publisher (publisher_name, publisher_id) VALUES ('F and W Publications Inc.', 661)
INTO publisher (publisher_name, publisher_id) VALUES ('F. Meiner', 662)
INTO publisher (publisher_name, publisher_id) VALUES ('Fab Press', 663)
INTO publisher (publisher_name, publisher_id) VALUES ('Faber Faber', 664)
INTO publisher (publisher_name, publisher_id) VALUES ('Faber and Faber', 665)
INTO publisher (publisher_name, publisher_id) VALUES ('Faber and Faber Limited', 666)
INTO publisher (publisher_name, publisher_id) VALUES ('Faber and Faber Ltd.', 667)
INTO publisher (publisher_name, publisher_id) VALUES ('Faber and Faber', 668)
INTO publisher (publisher_name, publisher_id) VALUES ('Faber and Faber and Penguin India', 669)
INTO publisher (publisher_name, publisher_id) VALUES ('FaithWords', 670)
INTO publisher (publisher_name, publisher_id) VALUES ('Fandemonium Books', 671)
INTO publisher (publisher_name, publisher_id) VALUES ('Fanfare', 672)
INTO publisher (publisher_name, publisher_id) VALUES ('Fantagraphics', 673)
INTO publisher (publisher_name, publisher_id) VALUES ('Fantagraphics Books', 674)
INTO publisher (publisher_name, publisher_id) VALUES ('Fantasy Flight Games', 675)
INTO publisher (publisher_name, publisher_id) VALUES ('Farrar Straus and Giroux', 676)
INTO publisher (publisher_name, publisher_id) VALUES ('Farrar Straus and Giroux', 677)
INTO publisher (publisher_name, publisher_id) VALUES ('Farrar Straus and Giroux (BYR)', 678)
INTO publisher (publisher_name, publisher_id) VALUES ('Farrar Straus and Giroux (NY)', 679)
INTO publisher (publisher_name, publisher_id) VALUES ('Farrar Strauss and Giroux-3pl', 680)
INTO publisher (publisher_name, publisher_id) VALUES ('Farrar Straus and Giroux', 681)
INTO publisher (publisher_name, publisher_id) VALUES ('Farrar Straus Giroux', 682)
INTO publisher (publisher_name, publisher_id) VALUES ('FASA Corp.', 683)
INTO publisher (publisher_name, publisher_id) VALUES ('FASA Corporation', 684)
INTO publisher (publisher_name, publisher_id) VALUES ('Fawcett', 685)
INTO publisher (publisher_name, publisher_id) VALUES ('Fawcett Books', 686)
INTO publisher (publisher_name, publisher_id) VALUES ('Fawcett Coventry', 687)
INTO publisher (publisher_name, publisher_id) VALUES ('Fawcett crest', 688)
INTO publisher (publisher_name, publisher_id) VALUES ('Fawcett Crest Books', 689)
INTO publisher (publisher_name, publisher_id) VALUES ('Feiwel and Friends', 690)
INTO publisher (publisher_name, publisher_id) VALUES ('Fellowship for the Performance', 691)
INTO publisher (publisher_name, publisher_id) VALUES ('Felony and Mayhem', 692)
INTO publisher (publisher_name, publisher_id) VALUES ('Feminist Press', 693)
INTO publisher (publisher_name, publisher_id) VALUES ('Feral House', 694)
INTO publisher (publisher_name, publisher_id) VALUES ('Festival', 695)
INTO publisher (publisher_name, publisher_id) VALUES ('Festival Books', 696)
INTO publisher (publisher_name, publisher_id) VALUES ('Filiquarian Publishing LLC.', 697)
INTO publisher (publisher_name, publisher_id) VALUES ('Findakly', 698)
INTO publisher (publisher_name, publisher_id) VALUES ('Firebird', 699)
INTO publisher (publisher_name, publisher_id) VALUES ('Firebird Books', 700)
INTO publisher (publisher_name, publisher_id) VALUES ('Firebrand Books', 701)
INTO publisher (publisher_name, publisher_id) VALUES ('Firelight Press', 702)
INTO publisher (publisher_name, publisher_id) VALUES ('Fireside', 703)
INTO publisher (publisher_name, publisher_id) VALUES ('Fireside Books', 704)
INTO publisher (publisher_name, publisher_id) VALUES ('First Avenue Editions (Tm)', 705)
INTO publisher (publisher_name, publisher_id) VALUES ('Fischer (Tb.)', 706)
INTO publisher (publisher_name, publisher_id) VALUES ('Fischer Taschenbuch Verlag', 707)
INTO publisher (publisher_name, publisher_id) VALUES ('Fischer TB', 708)
INTO publisher (publisher_name, publisher_id) VALUES ('Fithian Press', 709)
INTO publisher (publisher_name, publisher_id) VALUES ('Five Star (ME)', 710)
INTO publisher (publisher_name, publisher_id) VALUES ('Five Star Trade', 711)
INTO publisher (publisher_name, publisher_id) VALUES ('Flamingo', 712)
INTO publisher (publisher_name, publisher_id) VALUES ('Fleming H Revell Co', 713)
INTO publisher (publisher_name, publisher_id) VALUES ('Fleming H. Revell Company', 714)
INTO publisher (publisher_name, publisher_id) VALUES ('Focal Press', 715)
INTO publisher (publisher_name, publisher_id) VALUES ('Focus', 716)
INTO publisher (publisher_name, publisher_id) VALUES ('Focus on the Family Publishing', 717)
INTO publisher (publisher_name, publisher_id) VALUES ('Focus Publishing/R. Pullins Company', 718)
INTO publisher (publisher_name, publisher_id) VALUES ('Fodor''s', 719)
INTO publisher (publisher_name, publisher_id) VALUES ('Fulcrum Publishing', 746)
INTO publisher (publisher_name, publisher_id) VALUES ('Futura', 747)
INTO publisher (publisher_name, publisher_id) VALUES ('G. P. Putnam''s Sons', 748)
INTO publisher (publisher_name, publisher_id) VALUES ('G.P. Putnam''s Sons', 749)
INTO publisher (publisher_name, publisher_id) VALUES ('G.P. Putnam''s Sons Books for Young Readers', 750)
INTO publisher (publisher_name, publisher_id) VALUES ('Gaia Books', 751)
INTO publisher (publisher_name, publisher_id) VALUES ('Galahad Books', 752)
INTO publisher (publisher_name, publisher_id) VALUES ('Gale Cengage', 753)
INTO publisher (publisher_name, publisher_id) VALUES ('Gallery / Saga Press', 754)
INTO publisher (publisher_name, publisher_id) VALUES ('Gallery Books', 755)
INTO publisher (publisher_name, publisher_id) VALUES ('Houghton Mifflin Company', 986)
INTO publisher (publisher_name, publisher_id) VALUES ('Houghton Mifflin Harcourt', 987)
INTO publisher (publisher_name, publisher_id) VALUES ('Houghton Mifflin Harcourt P', 988)
INTO publisher (publisher_name, publisher_id) VALUES ('Houghton Mifflin/Seymour Lawrence', 989)
INTO publisher (publisher_name, publisher_id) VALUES ('House of Anansi Press', 990)
SELECT * FROM dual;

INSERT ALL
INTO publisher (publisher_name, publisher_id) VALUES ('House of Stratus', 991)
INTO publisher (publisher_name, publisher_id) VALUES ('Pinnacle', 1542)
INTO publisher (publisher_name, publisher_id) VALUES ('Pinter and Martin Ltd', 1543)
INTO publisher (publisher_name, publisher_id) VALUES ('Piper', 1544)
INTO publisher (publisher_name, publisher_id) VALUES ('Piper Taschenbuch', 1545)
INTO publisher (publisher_name, publisher_id) VALUES ('Piper Verlag', 1546)
INTO publisher (publisher_name, publisher_id) VALUES ('Pippin Publishing', 1547)
INTO publisher (publisher_name, publisher_id) VALUES ('Planeta', 1548)
INTO publisher (publisher_name, publisher_id) VALUES ('Planeta Publishing', 1549)
INTO publisher (publisher_name, publisher_id) VALUES ('Plaza and Janés', 1550)
INTO publisher (publisher_name, publisher_id) VALUES ('Plaza and Janes Editores S.A.', 1551)
INTO publisher (publisher_name, publisher_id) VALUES ('Plaza and Janés Editores S.A.', 1552)
INTO publisher (publisher_name, publisher_id) VALUES ('Plaza and Janes Editores Sa', 1553)
INTO publisher (publisher_name, publisher_id) VALUES ('Plaza and Janés Mexico', 1554)
INTO publisher (publisher_name, publisher_id) VALUES ('Plaza y Janes', 1555)
INTO publisher (publisher_name, publisher_id) VALUES ('Plaza y Janés', 1556)
INTO publisher (publisher_name, publisher_id) VALUES ('Plexus Publishing', 1557)
INTO publisher (publisher_name, publisher_id) VALUES ('Plexus Publishing Ltd', 1558)
INTO publisher (publisher_name, publisher_id) VALUES ('Plume', 1559)
INTO publisher (publisher_name, publisher_id) VALUES ('Plume (Penguin Books Ltd)', 1560)
INTO publisher (publisher_name, publisher_id) VALUES ('Plume Books', 1561)
INTO publisher (publisher_name, publisher_id) VALUES ('Pluto Press', 1562)
INTO publisher (publisher_name, publisher_id) VALUES ('Pocket', 1563)
INTO publisher (publisher_name, publisher_id) VALUES ('Pocket Books', 1564)
INTO publisher (publisher_name, publisher_id) VALUES ('Pocket Books / Simon and Schuster Inc.', 1565)
INTO publisher (publisher_name, publisher_id) VALUES ('Pocket Books: Gallery Books', 1566)
INTO publisher (publisher_name, publisher_id) VALUES ('Pocket Books/Simon and Schuster (NY)', 1567)
INTO publisher (publisher_name, publisher_id) VALUES ('Pocket Books/Star Trek', 1568)
INTO publisher (publisher_name, publisher_id) VALUES ('Pocket Star', 1569)
INTO publisher (publisher_name, publisher_id) VALUES ('Pocket Star Books', 1570)
INTO publisher (publisher_name, publisher_id) VALUES ('Pogue Press', 1571)
INTO publisher (publisher_name, publisher_id) VALUES ('Points', 1572)
INTO publisher (publisher_name, publisher_id) VALUES ('Poisoned Pen Press', 1573)
INTO publisher (publisher_name, publisher_id) VALUES ('Polity Press', 1574)
INTO publisher (publisher_name, publisher_id) VALUES ('Polychrome Publishing Corporation', 1575)
INTO publisher (publisher_name, publisher_id) VALUES ('Polyface', 1576)
INTO publisher (publisher_name, publisher_id) VALUES ('Polygon', 1577)
INTO publisher (publisher_name, publisher_id) VALUES ('Pomegranate Communications', 1578)
INTO publisher (publisher_name, publisher_id) VALUES ('Poorhouse Press', 1579)
INTO publisher (publisher_name, publisher_id) VALUES ('Poppy', 1580)
INTO publisher (publisher_name, publisher_id) VALUES ('Porrua', 1581)
INTO publisher (publisher_name, publisher_id) VALUES ('Portable Press', 1582)
INTO publisher (publisher_name, publisher_id) VALUES ('Portfolio', 1583)
INTO publisher (publisher_name, publisher_id) VALUES ('Poseidon Press', 1584)
INTO publisher (publisher_name, publisher_id) VALUES ('Possibilities', 1585)
INTO publisher (publisher_name, publisher_id) VALUES ('Potomac Books', 1586)
INTO publisher (publisher_name, publisher_id) VALUES ('Power Press', 1587)
INTO publisher (publisher_name, publisher_id) VALUES ('Praeger', 1588)
INTO publisher (publisher_name, publisher_id) VALUES ('Praeger Publishers', 1589)
INTO publisher (publisher_name, publisher_id) VALUES ('Pragmatic Bookshelf', 1590)
INTO publisher (publisher_name, publisher_id) VALUES ('Prentice Hall', 1591)
INTO publisher (publisher_name, publisher_id) VALUES ('Prentice Hall Press', 1592)
INTO publisher (publisher_name, publisher_id) VALUES ('Prentice Hall PTR', 1593)
INTO publisher (publisher_name, publisher_id) VALUES ('Prentice Hall/Library of Liberal Arts', 1594)
INTO publisher (publisher_name, publisher_id) VALUES ('Prentice Hall/Scribner/Macmillan', 1595)
INTO publisher (publisher_name, publisher_id) VALUES ('Prentice Hall/Simon and Schuster Company (Englewood Cliffs NJ)', 1596)
INTO publisher (publisher_name, publisher_id) VALUES ('Presidio Press', 1597)
INTO publisher (publisher_name, publisher_id) VALUES ('Presses de La Cite', 1598)
INTO publisher (publisher_name, publisher_id) VALUES ('Prestel Publishing', 1599)
INTO publisher (publisher_name, publisher_id) VALUES ('Prestwick House', 1600)
INTO publisher (publisher_name, publisher_id) VALUES ('Prestwick House - (Literary Touchstone Classic)', 1601)
INTO publisher (publisher_name, publisher_id) VALUES ('Price Stern Sloan', 1602)
INTO publisher (publisher_name, publisher_id) VALUES ('Prima Games', 1603)
INTO publisher (publisher_name, publisher_id) VALUES ('Prima Lifestyles', 1604)
INTO publisher (publisher_name, publisher_id) VALUES ('Princeton Architectural Press', 1605)
INTO publisher (publisher_name, publisher_id) VALUES ('Princeton University Press', 1606)
INTO publisher (publisher_name, publisher_id) VALUES ('Princeton University Press (NJ)', 1607)
INTO publisher (publisher_name, publisher_id) VALUES ('Profile Books', 1608)
INTO publisher (publisher_name, publisher_id) VALUES ('Project Management Institute', 1609)
INTO publisher (publisher_name, publisher_id) VALUES ('Prometheus Books', 1610)
INTO publisher (publisher_name, publisher_id) VALUES ('Providence Forum Press', 1611)
INTO publisher (publisher_name, publisher_id) VALUES ('Psychology Press', 1612)
INTO publisher (publisher_name, publisher_id) VALUES ('Public Square Books', 1613)
INTO publisher (publisher_name, publisher_id) VALUES ('PublicAffairs', 1614)
INTO publisher (publisher_name, publisher_id) VALUES ('Puffin', 1615)
INTO publisher (publisher_name, publisher_id) VALUES ('Puffin Audiobooks', 1616)
INTO publisher (publisher_name, publisher_id) VALUES ('Puffin Books', 1617)
INTO publisher (publisher_name, publisher_id) VALUES ('Puffin Books (Penguin Books)', 1618)
INTO publisher (publisher_name, publisher_id) VALUES ('Puffin Group', 1619)
INTO publisher (publisher_name, publisher_id) VALUES ('Punto de Lectura', 1620)
INTO publisher (publisher_name, publisher_id) VALUES ('Purple House Press', 1621)
INTO publisher (publisher_name, publisher_id) VALUES ('Push', 1622)
INTO publisher (publisher_name, publisher_id) VALUES ('Putnam', 1623)
INTO publisher (publisher_name, publisher_id) VALUES ('Putnam Adult', 1624)
INTO publisher (publisher_name, publisher_id) VALUES ('Putnam Publishing Group', 1625)
INTO publisher (publisher_name, publisher_id) VALUES ('Puzzle-Roca', 1626)
INTO publisher (publisher_name, publisher_id) VALUES ('Puzzle-Via Magna', 1627)
INTO publisher (publisher_name, publisher_id) VALUES ('Pygmalion Editions', 1628)
INTO publisher (publisher_name, publisher_id) VALUES ('Pyramid Books', 1629)
INTO publisher (publisher_name, publisher_id) VALUES ('Quality Paperback Book Club', 1630)
INTO publisher (publisher_name, publisher_id) VALUES ('Quarry Press', 1631)
INTO publisher (publisher_name, publisher_id) VALUES ('Quest Books', 1632)
INTO publisher (publisher_name, publisher_id) VALUES ('Quill', 1633)
INTO publisher (publisher_name, publisher_id) VALUES ('Quinteto', 1634)
INTO publisher (publisher_name, publisher_id) VALUES ('Raintree', 1635)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House', 1636)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House for Young Readers', 1637)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House Inc.', 1638)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House (NY)', 1639)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House (Vintage)', 1640)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House Anchor', 1641)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House Audio', 1642)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House Audio Publishing Group', 1643)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House Books for Young Readers', 1644)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House Children''s Books', 1645)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House for Young Readers', 1646)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House Inc.', 1647)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House Large Print', 1648)
INTO publisher (publisher_name, publisher_id) VALUES ('Random House Large Print Publishing', 1649)
INTO publisher (publisher_name, publisher_id) VALUES ('Stone Bridge Press', 1903)
INTO publisher (publisher_name, publisher_id) VALUES ('Stonewall Inn Editions', 1904)
INTO publisher (publisher_name, publisher_id) VALUES ('Storey Publishing LLC', 1905)
INTO publisher (publisher_name, publisher_id) VALUES ('Subterranean Press', 1906)
INTO publisher (publisher_name, publisher_id) VALUES ('Sudamericana', 1907)
INTO publisher (publisher_name, publisher_id) VALUES ('Suhrkamp', 1908)
INTO publisher (publisher_name, publisher_id) VALUES ('Suma', 1909)
INTO publisher (publisher_name, publisher_id) VALUES ('Suma de Letras Brasileiras', 1910)
INTO publisher (publisher_name, publisher_id) VALUES ('Sumach Press', 1911)
INTO publisher (publisher_name, publisher_id) VALUES ('Summit University Press', 1912)
INTO publisher (publisher_name, publisher_id) VALUES ('Sun and Moon Press', 1913)
INTO publisher (publisher_name, publisher_id) VALUES ('Sun and Moon Press', 1914)
INTO publisher (publisher_name, publisher_id) VALUES ('Sunburst', 1915)
INTO publisher (publisher_name, publisher_id) VALUES ('Sunstone Press', 1916)
INTO publisher (publisher_name, publisher_id) VALUES ('Sutton', 1917)
INTO publisher (publisher_name, publisher_id) VALUES ('Sutton Publishing', 1918)
INTO publisher (publisher_name, publisher_id) VALUES ('Swallow Press', 1919)
INTO publisher (publisher_name, publisher_id) VALUES ('Sweet Valley', 1920)
INTO publisher (publisher_name, publisher_id) VALUES ('TandT Clark Int''l', 1921)
INTO publisher (publisher_name, publisher_id) VALUES ('Tachyon Publications', 1922)
INTO publisher (publisher_name, publisher_id) VALUES ('Tanglewood', 1923)
INTO publisher (publisher_name, publisher_id) VALUES ('Tantor Media', 1924)
INTO publisher (publisher_name, publisher_id) VALUES ('Taplinger Publ. Company', 1925)
INTO publisher (publisher_name, publisher_id) VALUES ('Taplinger Publishing', 1926)
INTO publisher (publisher_name, publisher_id) VALUES ('Tarcher', 1927)
INTO publisher (publisher_name, publisher_id) VALUES ('Tarcherperigee', 1928)
INTO publisher (publisher_name, publisher_id) VALUES ('Taschen', 1929)
INTO publisher (publisher_name, publisher_id) VALUES ('Taunton Press', 1930)
INTO publisher (publisher_name, publisher_id) VALUES ('Tauris Parke Paperbacks', 1931)
INTO publisher (publisher_name, publisher_id) VALUES ('Taylor Productions Ltd', 1932)
INTO publisher (publisher_name, publisher_id) VALUES ('TEA', 1933)
INTO publisher (publisher_name, publisher_id) VALUES ('Teacher Created Resources', 1934)
INTO publisher (publisher_name, publisher_id) VALUES ('Teacher''s Pet Publications', 1935)
INTO publisher (publisher_name, publisher_id) VALUES ('Teacher''s Pet Publications Inc.', 1936)
INTO publisher (publisher_name, publisher_id) VALUES ('Teachers College Press', 1937)
INTO publisher (publisher_name, publisher_id) VALUES ('Teaching Resources', 1938)
INTO publisher (publisher_name, publisher_id) VALUES ('Temenos Press', 1939)
INTO publisher (publisher_name, publisher_id) VALUES ('Ten Speed Press', 1940)
INTO publisher (publisher_name, publisher_id) VALUES ('Texas AandM University Press', 1941)
INTO publisher (publisher_name, publisher_id) VALUES ('Th1nk Books', 1942)
INTO publisher (publisher_name, publisher_id) VALUES ('Thames Hudson', 1943)
INTO publisher (publisher_name, publisher_id) VALUES ('Thames and Hudson', 1944)
INTO publisher (publisher_name, publisher_id) VALUES ('Thames and Hudson Ltd', 1945)
INTO publisher (publisher_name, publisher_id) VALUES ('That Patchwork Place', 1946)
INTO publisher (publisher_name, publisher_id) VALUES ('The Audio Partners', 1947)
INTO publisher (publisher_name, publisher_id) VALUES ('The Berkley Publishing Group', 1948)
INTO publisher (publisher_name, publisher_id) VALUES ('The Bodley Head Ltd', 1949)
INTO publisher (publisher_name, publisher_id) VALUES ('The Chicken House', 1950)
INTO publisher (publisher_name, publisher_id) VALUES ('The Crossroad Publishing Company', 1951)
INTO publisher (publisher_name, publisher_id) VALUES ('The Disinformation Company (NYC)', 1952)
INTO publisher (publisher_name, publisher_id) VALUES ('The Guilford Press', 1953)
INTO publisher (publisher_name, publisher_id) VALUES ('The Harvill Press', 1954)
INTO publisher (publisher_name, publisher_id) VALUES ('The Liffey Press', 1955)
INTO publisher (publisher_name, publisher_id) VALUES ('The MIT Press', 1956)
INTO publisher (publisher_name, publisher_id) VALUES ('The Modern Library', 1957)
INTO publisher (publisher_name, publisher_id) VALUES ('The Modern Library New York', 1958)
INTO publisher (publisher_name, publisher_id) VALUES ('The Monacelli Press', 1959)
INTO publisher (publisher_name, publisher_id) VALUES ('The New Press', 1960)
INTO publisher (publisher_name, publisher_id) VALUES ('The New York Review Children''s Collection', 1961)
INTO publisher (publisher_name, publisher_id) VALUES ('The Orion Publishing Group Ltd', 1962)
INTO publisher (publisher_name, publisher_id) VALUES ('The Overlook Press', 1963)
INTO publisher (publisher_name, publisher_id) VALUES ('The Putnam and Grosset Group', 1964)
INTO publisher (publisher_name, publisher_id) VALUES ('Theatre Communications Group', 1965)
INTO publisher (publisher_name, publisher_id) VALUES ('Thomas Dunne Books', 1966)
INTO publisher (publisher_name, publisher_id) VALUES ('Thomas Nelson', 1967)
INTO publisher (publisher_name, publisher_id) VALUES ('Thomas Nelson Publishers', 1968)
INTO publisher (publisher_name, publisher_id) VALUES ('Thomas Publications (PA)', 1969)
INTO publisher (publisher_name, publisher_id) VALUES ('Thomas Y. Crowell Company', 1970)
INTO publisher (publisher_name, publisher_id) VALUES ('Thorndike Press', 1971)
INTO publisher (publisher_name, publisher_id) VALUES ('Thorndike Press Large Print', 1972)
SELECT * FROM dual;

INSERT ALL
INTO publisher (publisher_name, publisher_id) VALUES ('Three Rivers Press', 1973)
INTO publisher (publisher_name, publisher_id) VALUES ('Three Rivers Press (CA)', 1974)
INTO publisher (publisher_name, publisher_id) VALUES ('Thunder''s Mouth Press Books', 1975)
INTO publisher (publisher_name, publisher_id) VALUES ('Timber Press (OR)', 1976)
INTO publisher (publisher_name, publisher_id) VALUES ('Time Life Books', 1977)
INTO publisher (publisher_name, publisher_id) VALUES ('Time Life Medical', 1978)
INTO publisher (publisher_name, publisher_id) VALUES ('TIme Warner Books', 1979)
INTO publisher (publisher_name, publisher_id) VALUES ('Time Warner Books UK', 1980)
INTO publisher (publisher_name, publisher_id) VALUES ('Wiley', 2195)
INTO publisher (publisher_name, publisher_id) VALUES ('Wiley (TP)', 2196)
INTO publisher (publisher_name, publisher_id) VALUES ('Wiley Publishing', 2197)
INTO publisher (publisher_name, publisher_id) VALUES ('Wiley Publishing Inc.', 2198)
INTO publisher (publisher_name, publisher_id) VALUES ('Wiley-Blackwell', 2199)
INTO publisher (publisher_name, publisher_id) VALUES ('Wilhelm Goldmann Verlag GmbH', 2200)
INTO publisher (publisher_name, publisher_id) VALUES ('William B. Eerdmans Publishing Company', 2201)
INTO publisher (publisher_name, publisher_id) VALUES ('William Heinemann', 2202)
INTO publisher (publisher_name, publisher_id) VALUES ('William Heinemann Ltd.', 2203)
INTO publisher (publisher_name, publisher_id) VALUES ('William Morrow', 2204)
INTO publisher (publisher_name, publisher_id) VALUES ('William Morrow / Harper', 2205)
INTO publisher (publisher_name, publisher_id) VALUES ('William Morrow / HarperCollins / Harper Perennial', 2206)
INTO publisher (publisher_name, publisher_id) VALUES ('William Morrow and Company', 2207)
INTO publisher (publisher_name, publisher_id) VALUES ('William Morrow and Company Inc.', 2208)
INTO publisher (publisher_name, publisher_id) VALUES ('William Morrow and Company (NYC)', 2209)
INTO publisher (publisher_name, publisher_id) VALUES ('William Morrow Paperbacks', 2210)
INTO publisher (publisher_name, publisher_id) VALUES ('William Morrow 1ST edition', 2211)
INTO publisher (publisher_name, publisher_id) VALUES ('Windsor Golden Series', 2212)
INTO publisher (publisher_name, publisher_id) VALUES ('Wings', 2213)
INTO publisher (publisher_name, publisher_id) VALUES ('Wings Books', 2214)
INTO publisher (publisher_name, publisher_id) VALUES ('Winter on the Farm (My First Little House)', 2215)
INTO publisher (publisher_name, publisher_id) VALUES ('Wipf and Stock Publishers', 2216)
INTO publisher (publisher_name, publisher_id) VALUES ('Wisdom Publications', 2217)
INTO publisher (publisher_name, publisher_id) VALUES ('Wizarding World Press', 2218)
INTO publisher (publisher_name, publisher_id) VALUES ('Wizards of the Coast', 2219)
INTO publisher (publisher_name, publisher_id) VALUES ('Woodbridge Press Publishing Company', 2220)
INTO publisher (publisher_name, publisher_id) VALUES ('Woodrow Wilson Center Press / Johns Hopkins University Press', 2221)
INTO publisher (publisher_name, publisher_id) VALUES ('Wordsworth Classics', 2222)
INTO publisher (publisher_name, publisher_id) VALUES ('Wordsworth Editions', 2223)
INTO publisher (publisher_name, publisher_id) VALUES ('Workman Publishing Company', 2224)
INTO publisher (publisher_name, publisher_id) VALUES ('World Wrestling Entertainment Books', 2225)
INTO publisher (publisher_name, publisher_id) VALUES ('Worth Publishers', 2226)
INTO publisher (publisher_name, publisher_id) VALUES ('Writer''s Digest Books', 2227)
INTO publisher (publisher_name, publisher_id) VALUES ('Wyatt Book', 2228)
INTO publisher (publisher_name, publisher_id) VALUES ('Xlibris Corporation', 2229)
INTO publisher (publisher_name, publisher_id) VALUES ('Xulon Press', 2230)
INTO publisher (publisher_name, publisher_id) VALUES ('Y Lolfa', 2231)
INTO publisher (publisher_name, publisher_id) VALUES ('Yale University Press', 2232)
INTO publisher (publisher_name, publisher_id) VALUES ('Yale University Press (New Haven CT)', 2233)
INTO publisher (publisher_name, publisher_id) VALUES ('Yapı Kredi Yayınları', 2234)
INTO publisher (publisher_name, publisher_id) VALUES ('Yearling', 2235)
INTO publisher (publisher_name, publisher_id) VALUES ('Yearling Books', 2236)
INTO publisher (publisher_name, publisher_id) VALUES ('Yellow Jersey', 2237)
INTO publisher (publisher_name, publisher_id) VALUES ('Yesterday''s Classics', 2238)
INTO publisher (publisher_name, publisher_id) VALUES ('York Press', 2239)
INTO publisher (publisher_name, publisher_id) VALUES ('Yoruba Theological Archministry', 2240)
INTO publisher (publisher_name, publisher_id) VALUES ('Yosemite Conservancy', 2241)
INTO publisher (publisher_name, publisher_id) VALUES ('Young Picador', 2242)
INTO publisher (publisher_name, publisher_id) VALUES ('YoungJin Singapore Pte. Ltd.', 2243)
INTO publisher (publisher_name, publisher_id) VALUES ('Your Coach Digital', 2244)
INTO publisher (publisher_name, publisher_id) VALUES ('Zebra', 2245)
INTO publisher (publisher_name, publisher_id) VALUES ('Zebra Books', 2246)
INTO publisher (publisher_name, publisher_id) VALUES ('Zenith Press', 2247)
INTO publisher (publisher_name, publisher_id) VALUES ('Zeta Bolsillo', 2248)
INTO publisher (publisher_name, publisher_id) VALUES ('Zondervan', 2249)
INTO publisher (publisher_name, publisher_id) VALUES ('Zondervan Publishing Company', 2250)
INTO publisher (publisher_name, publisher_id) VALUES ('Zondervan Publishing House', 2251)
INTO publisher (publisher_name, publisher_id) VALUES ('Эксмо', 2252)
INTO publisher (publisher_name, publisher_id) VALUES ('ガンガンコミックス', 2253)
INTO publisher (publisher_name, publisher_id) VALUES ('ビブロス', 2254)
INTO publisher (publisher_name, publisher_id) VALUES ('小学館', 2255)
INTO publisher (publisher_name, publisher_id) VALUES ('小学館 [Shōgakukan]', 2256)
INTO publisher (publisher_name, publisher_id) VALUES ('時報出版', 2257)
INTO publisher (publisher_name, publisher_id) VALUES ('東立', 2258)
INTO publisher (publisher_name, publisher_id) VALUES ('皇冠文化出版有限公司', 2259)
INTO publisher (publisher_name, publisher_id) VALUES ('聯經出版事業股份有限公司', 2260)
INTO publisher (publisher_name, publisher_id) VALUES ('英文漢聲出版股份有限公司', 2261)
INTO publisher (publisher_name, publisher_id) VALUES ('角川書店 (Kadokawa Shoten)', 2262)
INTO publisher (publisher_name, publisher_id) VALUES ('講談社', 2263)
INTO publisher (publisher_name, publisher_id) VALUES ('集英社', 2264)
SELECT * FROM dual;

COMMIT;
